<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-biz</artifactId>
        <groupId>com.midea</groupId>
        <version>1.0-russia-PROJECT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloud-biz-gateway-pj</artifactId>
    <version>1.0-russia-SNAPSHOT</version>
    <packaging>jar</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-openfeign-dependencies</artifactId>
                <version>2.1.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-commons-pj</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-commons-extend</artifactId>
            <version>meiqing-V3.0.11.1</version>
        </dependency>

        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>base-component-extend</artifactId>
            <version>${srm-project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.baomidou</groupId>
                    <artifactId>mybatis-plus-boot-starter</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.mideacloud</groupId>
                    <artifactId>price-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.mideacloud</groupId>
                    <artifactId>partner-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-gateway-extend</artifactId>
            <version>${srm-project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.mideacloud</groupId>
                    <artifactId>price-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.mideacloud</groupId>
                    <artifactId>partner-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.4.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.1.4.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <classifier>boot</classifier>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
