alter table scc_sup_company_info modify FLOW_REMARK text null comment '审批备注';

ALTER TABLE scc_sup_company_info
ADD EXT_REJECT_ATTRIBUTE1 VARCHAR(100) NULL COMMENT '批注1',
ADD EXT_REJECT_ATTRIBUTE2 VARCHAR(100) NULL COMMENT '批注2',
ADD EXT_REJECT_ATTRIBUTE3 VARCHAR(100) NULL COMMENT '批注3',
ADD EXT_REJECT_ATTRIBUTE4 VARCHAR(100) NULL COMMENT '批注4',
ADD EXT_REJECT_ATTRIBUTE5 VARCHAR(100) NULL COMMENT '批注5',
ADD EXT_REJECT_ATTRIBUTE6 VARCHAR(100) NULL COMMENT '批注6',
ADD EXT_REJECT_ATTRIBUTE7 VARCHAR(100) NULL COMMENT '批注7',
ADD EXT_REJECT_ATTRIBUTE8 VARCHAR(100) NULL COMMENT '批注8',
ADD EXT_REJECT_ATTRIBUTE9 VARCHAR(100) NULL COMMENT '批注9',
ADD EXT_REJECT_ATTRIBUTE10 VARCHAR(100) NULL COMMENT '批注10',
ADD EXT_REJECT_ATTRIBUTE11 VARCHAR(100) NULL COMMENT '批注11',
ADD EXT_REJECT_ATTRIBUTE12 VARCHAR(100) NULL COMMENT '批注12',
ADD EXT_REJECT_ATTRIBUTE13 VARCHAR(100) NULL COMMENT '批注13',
ADD EXT_REJECT_ATTRIBUTE14 VARCHAR(100) NULL COMMENT '批注14',
ADD EXT_REJECT_ATTRIBUTE15 VARCHAR(100) NULL COMMENT '批注15',
ADD EXT_REJECT_ATTRIBUTE16 VARCHAR(100) NULL COMMENT '批注16',
ADD EXT_REJECT_ATTRIBUTE17 VARCHAR(100) NULL COMMENT '批注17',
ADD EXT_REJECT_ATTRIBUTE18 VARCHAR(100) NULL COMMENT '批注18',
ADD EXT_REJECT_ATTRIBUTE19 VARCHAR(100) NULL COMMENT '批注19',
ADD EXT_REJECT_ATTRIBUTE20 VARCHAR(100) NULL COMMENT '批注20';