<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sdk-project-impl</artifactId>
        <groupId>com.midea</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sdk-project-sou-impl</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.91.Final</version>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>sdk-sou-interface</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.googlecode.aviator</groupId>
                    <artifactId>aviator</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>icepdf-core</artifactId>
                    <groupId>org.icepdf.os</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>sou-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>sdk-project-entity</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-api-pj</artifactId>
            <version>1.0-russia-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.googlecode.aviator</groupId>
                    <artifactId>aviator</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-commons-pj</artifactId>
            <version>1.0-russia-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.googlecode.aviator</groupId>
                    <artifactId>aviator</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>icepdf-core</artifactId>
                    <groupId>org.icepdf.os</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>e-iceblue</groupId>
            <artifactId>spire.pdf.free</artifactId>
            <version>5.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.dromara.x-easypdf</groupId>
            <artifactId>x-easypdf</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>cn.afterturn</groupId>
            <artifactId>easypoi-base</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.afterturn</groupId>
            <artifactId>easypoi-web</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.afterturn</groupId>
            <artifactId>easypoi-annotation</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose-words</artifactId>
            <version>18.6.2</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.2</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeArtifactIds>
                                sdk-project-entity,cloud-biz-api-pj,cloud-biz-commons-pj,spire.pdf.free,
                                feign-slf4j,
                                auth,
                                s3,
                                jna,
                                osca-common,
                                ies-common,
                                huaweicloud-sdk-core,
                                profiles,
                                eventstream,
                                jopt-simple,
                                utils,
                                ies-sdk,
                                third-party-jackson-core,
                                parent-join-client,
                                sdk-core,
                                esdk-obs-java,
                                elasticsearch,
                                joda-time,
                                stax-api,
                                cpdetector,
                                aliyun-java-sdk-core,
                                ies-core,
                                aws-query-protocol,
                                jdom2,
                                aws-xml-protocol,
                                compiler,
                                logging-interceptor,
                                jettison,
                                aws-core,
                                hppc,
                                tencentcloud-sdk-java-kms,
                                huaweicloud-sdk-iam,
                                aggs-matrix-stats-client,
                                aliyun-java-sdk-ram,
                                netty-nio-client,
                                protocol-core,
                                tencentcloud-sdk-java-common,
                                simple-xml-safe,
                                mapper-extras-client,
                                rank-eval-client,
                                aliyun-sdk-oss,
                                osca-core,
                                regions,
                                paas-boot-core-starter,
                                aliyun-java-sdk-ecs,
                                minio,
                                cos-sts_api,
                                t-digest,
                                jackson-dataformat-smile,
                                jackson-dataformat-cbor,
                                elasticsearch-x-content,
                                arns,
                                metrics-spi,
                                aliyun-java-sdk-sts,
                                http-client-spi,
                                aliyun-java-sdk-kms,
                                json-utils,
                                lang-mustache-client,
                                cos_api,
                                aspose-words,
                                easypoi-web,
                                easypoi-annotation,
                                easypoi-base,
                                x-easypdf,
                                x-easypdf-pdfbox,
                                x-easypdf-fop,
                                pdfbox,
                                fontbox,
                                preflight,
                                xmpbox,
                                pdfbox-tools,
                                pdfbox-io
                            </includeArtifactIds>
                            <includeGroupIds>
                                com.midea,e-iceblue,io.github.openfeign,software.amazon.awssdk,org.elasticsearch,org.apache.lucene,org.elasticsearch.client,com.meicloud.paas,com.huaweicloud.sdk,software.amazon.eventstream,net.sf.jopt-simple,com.midea,org.elasticsearch.plugin,com.huaweicloud,joda-time,stax,com.github.jiangxincode,com.aliyun,org.jdom,com.github.spullara.mustache.java,com.squareup.okhttp,org.codehaus.jettison,com.carrotsearch,com.tencentcloudapi,com.carrotsearch.thirdparty,com.aliyun.oss,io.minio,com.qcloud,com.tdunning,com.fasterxml.jackson.dataformat,com.aspose,cn.afterturn,org.dromara.x-easypdf,org.apache.pdfbox
                            </includeGroupIds>
                            <excludeGroupIds>
                                com.mideacloud
                            </excludeGroupIds>
                            <excludeArtifactIds>
                                icepdf-core
                            </excludeArtifactIds>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <excludeTransitive>false</excludeTransitive>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
            <resource>
                <directory>../sdk-project-entity/target/classes/</directory>
                <includes>
                    <include>**/*</include>
                </includes>
                <targetPath>../sdk-project-entity</targetPath>
            </resource>
        </resources>

    </build>
</project>
