ALTER TABLE `scc_contract_head`
   ADD COLUMN `EXT_CONTRACT_HANDLER_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '合同经办人ID' ,
	ADD COLUMN `EXT_PRICE_POOL_FLAG` VARCHAR(5) NULL DEFAULT NULL COMMENT '是否进价格库' ,
	ADD COLUMN `EXT_SCORE_FLAG` VARCHAR(5) NULL DEFAULT NULL COMMENT '是否需要评分',
	ADD COLUMN `EXT_INVEST_NO` VARCHAR(30) NULL DEFAULT NULL;

ALTER TABLE `scc_contract_pay_plan`
    ADD COLUMN `EXT_ACCEPTANCE_DATE` DATE NULL DEFAULT NULL COMMENT '承兑期限' ,
	ADD COLUMN `EXT_ACCEPTANCE_RATIO` INT NULL DEFAULT NULL COMMENT '承兑比例' ,
	ADD COLUMN `EXT_WIRE_TRANSFER_RATIO` INT NULL DEFAULT NULL COMMENT '电汇比例' ;

CREATE TABLE IF NOT EXISTS `scc_contract_stamp_annex`
(
    `STAMP_ANNEX_ID`         BIGINT(20) NOT NULL COMMENT '类型-盖章附件Id',
    `CONTRACT_HEAD_ID`       BIGINT(20) NULL DEFAULT NULL COMMENT '合同头信息ID',
    `FILE_SOURCE_NAME`       VARCHAR(1000) NULL DEFAULT NULL COMMENT '原始文件名' COLLATE 'utf8mb4_unicode_ci',
    `FILEUPLOAD_ID`          BIGINT(20) NULL DEFAULT NULL COMMENT '文件ID',
    `CHANGE_FIELD`           VARCHAR(10) NULL DEFAULT NULL COMMENT '变更字段(N/Y)' COLLATE 'utf8mb4_unicode_ci',
    `CREATED_ID`             BIGINT(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             VARCHAR(50)  NOT NULL COMMENT '创建人' COLLATE 'utf8mb4_unicode_ci',
    `CREATION_DATE`          DATETIME     NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          VARCHAR(150) NOT NULL COMMENT '创建人IP' COLLATE 'utf8mb4_unicode_ci',
    `CREATED_FULL_NAME`      VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' COLLATE 'utf8mb4_unicode_ci',
    `LAST_UPDATED_ID`        BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' COLLATE 'utf8mb4_unicode_ci',
    `LAST_UPDATE_DATE`       DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' COLLATE 'utf8mb4_unicode_ci',
    `LAST_UPDATED_FULL_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' COLLATE 'utf8mb4_unicode_ci',
    `TENANT_ID`              VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' COLLATE 'utf8mb4_unicode_ci',
    `VERSION`                BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    `SOURCE_ID`              BIGINT(20) NULL DEFAULT NULL COMMENT '原合同附件ID',
    `CEEA_UPLOAD_TIME`       DATETIME NULL DEFAULT NULL COMMENT '上传时间',
    `FILE_TYPE`              VARCHAR(100) NULL DEFAULT NULL COMMENT '附件类型' COLLATE 'utf8mb4_unicode_ci',
    `DEL`                    VARCHAR(10) NULL DEFAULT NULL COMMENT '是否允许删除，给前端做判断' COLLATE 'utf8mb4_unicode_ci',
    PRIMARY KEY (`STAMP_ANNEX_ID`) USING BTREE,
    INDEX                    `SCC_CONTRACT_STAMP_ANNEX_N1` (`CONTRACT_HEAD_ID`) USING BTREE
) COMMENT='盖章合同附件表'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;

CREATE TABLE IF NOT EXISTS `scc_contract_operation_log`
(
    `OPERATION_LOG_ID`       BIGINT(20) NOT NULL COMMENT '类型-操作Id',
    `CONTRACT_HEAD_ID`       BIGINT(20) NULL DEFAULT NULL COMMENT '合同头信息ID',
    `OPERATION_TYPE`         VARCHAR(50)  NOT NULL COMMENT '操作类型' COLLATE 'utf8mb4_unicode_ci',
    `OPERATION_DESC`         VARCHAR(5000) NULL DEFAULT NULL COMMENT '操作描述' COLLATE 'utf8mb4_unicode_ci',
    `CREATED_ID`             BIGINT(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             VARCHAR(50)  NOT NULL COMMENT '创建人' COLLATE 'utf8mb4_unicode_ci',
    `CREATION_DATE`          DATETIME     NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          VARCHAR(150) NOT NULL COMMENT '创建人IP' COLLATE 'utf8mb4_unicode_ci',
    `CREATED_FULL_NAME`      VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' COLLATE 'utf8mb4_unicode_ci',
    `LAST_UPDATED_ID`        BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' COLLATE 'utf8mb4_unicode_ci',
    `LAST_UPDATE_DATE`       DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' COLLATE 'utf8mb4_unicode_ci',
    `LAST_UPDATED_FULL_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' COLLATE 'utf8mb4_unicode_ci',
    `TENANT_ID`              VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' COLLATE 'utf8mb4_unicode_ci',
    `VERSION`                BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`OPERATION_LOG_ID`) USING BTREE,
    INDEX                    `SCC_CONTRACT_OPERATON_LOG_N1` (`CONTRACT_HEAD_ID`) USING BTREE
) COMMENT='操作记录表'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;

CREATE TABLE IF NOT EXISTS `scc_contract_basis_annex` (
	`BASIS_ANNEX_ID` BIGINT(20) NOT NULL COMMENT '合同依据附件Id',
	`CONTRACT_HEAD_ID` BIGINT(20) NOT NULL COMMENT '合同头信息ID',
	`FILE_SOURCE_NAME` VARCHAR(1000) NULL DEFAULT NULL COMMENT '原始文件名' COLLATE 'utf8mb4_unicode_ci',
	`FILEUPLOAD_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '文件ID',
	`CHANGE_FIELD` VARCHAR(10) NULL DEFAULT NULL COMMENT '变更字段(N/Y)' COLLATE 'utf8mb4_unicode_ci',
	`CREATED_ID` BIGINT(20) NOT NULL COMMENT '创建人ID',
	`CREATED_BY` VARCHAR(50) NOT NULL COMMENT '创建人' COLLATE 'utf8mb4_unicode_ci',
	`CREATION_DATE` DATETIME NOT NULL COMMENT '创建时间',
	`CREATED_BY_IP` VARCHAR(150) NOT NULL COMMENT '创建人IP' COLLATE 'utf8mb4_unicode_ci',
	`CREATED_FULL_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' COLLATE 'utf8mb4_unicode_ci',
	`LAST_UPDATED_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
	`LAST_UPDATED_BY` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' COLLATE 'utf8mb4_unicode_ci',
	`LAST_UPDATE_DATE` DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
	`LAST_UPDATED_BY_IP` VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' COLLATE 'utf8mb4_unicode_ci',
	`LAST_UPDATED_FULL_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' COLLATE 'utf8mb4_unicode_ci',
	`TENANT_ID` VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' COLLATE 'utf8mb4_unicode_ci',
	`VERSION` BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	`SOURCE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '原合同附件ID',
	`CEEA_UPLOAD_TIME` DATETIME NULL DEFAULT NULL COMMENT '上传时间',
	`FILE_TYPE` VARCHAR(100) NULL DEFAULT NULL COMMENT '附件类型' COLLATE 'utf8mb4_unicode_ci',
	`DEL` VARCHAR(10) NULL DEFAULT NULL COMMENT '是否允许删除，给前端做判断' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`BASIS_ANNEX_ID`) USING BTREE,
	INDEX `SCC_CONTRACT_BASIS_ANNEX_N1` (`CONTRACT_HEAD_ID`) USING BTREE
)
COMMENT='合同依据附件表'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;



ALTER TABLE `scc_cont_per_plan_milestone`
    ADD COLUMN `EXT_CREATE_PERFORM_FLAG` VARCHAR(5) NULL DEFAULT NULL COMMENT '是否已创绩效评分项目' AFTER `DELIVERY_BUTTON`;

ALTER TABLE `scc_cont_per_pay_plan`
   ADD COLUMN `EXT_ACCEPTANCE_DATE` DATE NULL DEFAULT NULL COMMENT '承兑期限' AFTER `INVOICE_NO`,
	ADD COLUMN `EXT_ACCEPTANCE_RATIO` INT NULL DEFAULT NULL COMMENT '承兑比例' AFTER `EXT_ACCEPTANCE_DATE`,
	ADD COLUMN `EXT_WIRE_TRANSFER_RATIO` INT NULL DEFAULT NULL COMMENT '电汇比例' AFTER `EXT_ACCEPTANCE_RATIO`;

CREATE TABLE `scc_contract_no_seq`
(
    `CONTRACT_NO_SEQ_ID`     BIGINT(20) NOT NULL COMMENT '序列主Id',
    `CONTRACT_HEAD_ID`       BIGINT(20) NOT NULL COMMENT '原合同ID',
    `CONTRACT_NO`            VARCHAR(30)  NOT NULL COMMENT '合同号',
    `CONTRACT_EXT_MAX_SEQ`   BIGINT(20) NOT NULL COMMENT '合同最大序列',
    `CREATED_ID`             BIGINT(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             VARCHAR(50)  NOT NULL COMMENT '创建人' COLLATE 'utf8mb4_general_ci',
    `CREATION_DATE`          DATETIME     NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          VARCHAR(150) NOT NULL COMMENT '创建人IP' COLLATE 'utf8mb4_general_ci',
    `CREATED_FULL_NAME`      VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' COLLATE 'utf8mb4_general_ci',
    `LAST_UPDATED_ID`        BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' COLLATE 'utf8mb4_general_ci',
    `LAST_UPDATE_DATE`       DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' COLLATE 'utf8mb4_general_ci',
    `LAST_UPDATED_FULL_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' COLLATE 'utf8mb4_general_ci',
    `TENANT_ID`              VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' COLLATE 'utf8mb4_general_ci',
    `VERSION`                BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`CONTRACT_NO_SEQ_ID`) USING BTREE,
    INDEX                    `SCC_CONTRACT_SEQ_N1` (`CONTRACT_HEAD_ID`) USING BTREE
) COMMENT='合同补充协议号序列'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

ALTER TABLE `scc_contract_head`
   ADD COLUMN `EXT_SECTOR_ID` BIGINT NULL DEFAULT NULL COMMENT '板块ID' ,
   ADD COLUMN `EXT_SECTOR_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '板块名称' ,
	ADD COLUMN `EXT_SECTOR_CODE` VARCHAR(30) NULL DEFAULT NULL COMMENT '板块代码' ,
	ADD COLUMN `EXT_EVALUATE_FLAG` VARCHAR(5) NULL DEFAULT NULL COMMENT '是否免评分' ,
	ADD COLUMN `EXT_CATEGORY_ID` BIGINT NULL DEFAULT NULL COMMENT '品类ID' ,
	ADD COLUMN `EXT_CATEGORY_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '品类名称' ,
	ADD COLUMN `EXT_CATEGORY_CODE` VARCHAR(30) NULL DEFAULT NULL COMMENT '品类代码';

ALTER TABLE `scc_contract_head`
    ADD COLUMN `EXT_FIX_PRICE_NO` VARCHAR(30) NULL DEFAULT NULL COMMENT '临采定价单号';

ALTER TABLE `scc_contract_head`
    ADD COLUMN `EXT_CONTRACT_HANDLER_NAME` VARCHAR (50) NULL DEFAULT NULL COMMENT '经办人名称' COLLATE 'utf8mb4_general_ci';
    
    

ALTER TABLE `scc_contract_head`
    ADD COLUMN `EXT_FIX_PRICE_LINE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '临采定价单ID';

ALTER TABLE `scc_contract_material`
    ADD COLUMN `EXT_INVOICE_TYPE`  VARCHAR(50) NULL DEFAULT NULL COMMENT '发票类型';

ALTER TABLE `scc_contract_head`
    ADD COLUMN `EXT_STAMP_SIGN_SEQ` VARCHAR(30) NULL DEFAULT NULL COMMENT '签约顺序，VENDOR_FIRST/对方先签，COMPANY_FIRST/我方先签';

ALTER TABLE `scc_contract_model_head`
    ADD COLUMN `EXT_NO_EXAMINE_FLAG` VARCHAR(5) NULL DEFAULT 'Y' COMMENT '是否免审批' COLLATE 'utf8mb4_general_ci';

ALTER TABLE `scc_contract_partner`
    ADD COLUMN `EXT_EMPLOYEE_NUMBER` VARCHAR(30) NULL DEFAULT NULL COMMENT '工号';

ALTER TABLE `scc_contract_material`
    ADD COLUMN `EXT_FIX_PRICE_LINE_ID` BIGINT NULL DEFAULT NULL COMMENT '临采定价单行ID';

ALTER TABLE `scc_contract_head`
    ADD COLUMN `EXT_CONTENT_FINAL` LONGTEXT NULL DEFAULT NULL COMMENT '最终合同正文html' COLLATE 'utf8mb4_general_ci';
    
ALTER TABLE `scc_contract_head`
	ADD COLUMN `EXT_INVITE_FINISH_DATE`DATE NULL DEFAULT NULL COMMENT '招标完成时间' ;

ALTER TABLE `scc_contract_head`
	ADD COLUMN `EXT_INVITE_HEAD_ID`  BIGINT(20) NULL DEFAULT NULL COMMENT '招标负责人ID ';

ALTER TABLE `scc_contract_head`
    ADD COLUMN `EXT_CONTRACT_HANDLER_ACCOUNT`  VARCHAR(30) NULL DEFAULT NULL COMMENT '经办人账号';


	  








