
ALTER TABLE `scc_cont_per_acceptance`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_contract_head`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';