iam.redis.database=5
 
#mysql-common
iam.db.host=${global.db.host}
iam.db.port=${global.db.port}
iam.db.username=${global.db.username}
iam.db.password=${global.db.password}
 
#mysql-database-name
iam.db.schema=${global.mysqldb.prefix}iam
 
#mail notice
#iam.mail.host=mail.midea.com
#iam.mail.username=iam@midea.com
#iam.mail.password=abc
iam.mail.host=mail.gwmdc.com
iam.mail.username=zbgys@gwmdc.com
iam.mail.password=qaz@123.com
 
#\u5BA1\u8BA1\u65E5\u5FD7
#\u9ED8\u8BA4iam
iam.audit.app-code=iam
#\u9ED8\u8BA4e7e7fb5463c411eda453020017000b7b
iam.audit.app-secret=e7e7fb5463c411eda453020017000b7b
 
#xxl
iam.xxljob.appname=${spring.application.name}-srm-midea-module
# .local
iam.xxljob.jobs.callback.ip=iam-java-jobs-srm-midea-module.srm-midea-module.svc.cluster.dev 
# .local
iam.xxljob.permanal.callback.ip=iam-java-permanal-srm-midea-module.srm-midea-module.svc.cluster.dev

#app-config
iam.host=${global.iam.domain}
iam.tenant-model= single

iam.protocol=${global.httpProtocol}

#jasypt:??????
iam.jasypt.encryptor.passwd=43D8OchKs9qPm0_V

iam.redis.sentinel.master=${global.redis.sentinel.master}
iam.redis.sentinel.nodes=${global.redis.sentinel.nodes}