create table scc_npm_sou_fix_price_head (
    FIX_PRICE_HEAD_ID               bigint(20)                      not null primary key,
    FIX_PRICE_NO                    varchar(50)                     not null comment '定价单号',
    FIX_PRICE_DATE                  date                            null comment '申请日期',
    ORG_DEP_ID                      bigint(20)                      null comment '采购部门ID',
    ORG_DEP_CODE                    varchar(80)                     null comment '采购部门编码',
    ORG_DEP_NAME                    varchar(255)                    null comment '采购部门名称',
    FIX_PRICE_STATUS                varchar(20)                     not null comment '定价状态 EXT_FIX_PRICE_STATUS',
    TOTAL_NOTAX_PRICE               decimal(24,8)                   null comment '总金额(未税)',
    TOTAL_TAX_PRICE                 decimal(24,8)                   null comment '价税合计(含税)',
    PAYMENT_METHOD                  varchar(20)                     null comment '付款方式 EXT_SOU_FIX_PRICE_PAYMENT_METHOD',
    PAYMENT_TERM                    varchar(100)                    null comment '付款条款',
    REMARK                          text                            null comment '备注',
    CAN_SUBMIT                      char(1)                         not null default 'N' comment '是否可提交',

    CREATED_ID                      bigint                          not null comment '创建人ID',
    CREATED_BY                      varchar(50)                     not null comment '创建人',
    CREATION_DATE                   datetime                        not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)                    not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)                    null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint                          null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)                     null comment '更新人',
    LAST_UPDATE_DATE                datetime                        null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)                    null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)                    null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)                     null comment '租户ID',
    VERSION                         bigint     default 0            null comment '版本号'
) comment '长城定价单头表';

create table scc_npm_sou_fix_price_line (
    FIX_PRICE_LINE_ID               bigint(20)                      not null primary key,
    FIX_PRICE_HEAD_ID               bigint(20)                      not null comment '定价单ID',
    FIX_PRICE_NO                    varchar(50)                     not null comment '定价单号',
    SOURCE_FROM_TYPE                varchar(20)                     not null comment '来源类型(EXT_SOU_FIX_PRICE_LINE_FROM_TYPE)',
    SOURCE_FROM_LINE_ID             varchar(50)                     not null comment '来源单据明细ID',
    SOURCE_FROM_ID                  varchar(50)                     null comment '来源单据ID',
    SOURCE_FROM_NO                  varchar(50)                     null comment '来源单据编号',
    REQUIREMENT_LINE_IDS            varchar(300)                    null comment '从询比价过来拿到的关联需求池ID集合',
    ORG_OU_ID                       bigint(20)                      null comment '业务实体ID(申请单位)',
    ORG_OU_CODE                     varchar(50)                     null comment '业务实体编码(申请单位)',
    ORG_OU_NAME                     varchar(50)                     null comment '业务实体名称(申请单位)',
    ITEM_ID                         bigint(20)                      null comment '物料ID',
    ITEM_CODE                       varchar(80)                     null comment '物料编码',
    ITEM_DESC                       varchar(255)                    null comment '物料名称',
    EXT_MATERIAL_MODEL              varchar(255)                    null comment '物料规格型号',
    UNIT                            varchar(15)                     null comment '单位',
    QUANTITY                        decimal(24,8)                   null comment '单位',
    BRAND                           varchar(50)                     null comment '品牌',
    VENDOR_ID                       bigint(20)                      null comment '供应商ID',
    VENDOR_CODE                     varchar(50)                     null comment '供应商编码',
    VENDOR_NAME                     varchar(255)                    null comment '供应商名称',
    CURRENCY_CODE                   varchar(15)                     null comment '币种',
    NOTAX_PRICE                     decimal(24,8)                   null comment '未税单价',
    TAX_KEY                         varchar(20)                     null comment '税率编码',
    TAX_RATE                        decimal(24,8)                   null comment '税率值',
    NOTAX_TOTAL_PRICE               decimal(24,8)                   null comment '未税总价',
    LATEST_MIN_NOTAX_PRICE          decimal(24,8)                   null comment '近期最低价格(未税)',
    PRICE_FLOAT_SCALE               decimal(8,4)                    null comment '浮动比例',
    LATEST_MIN_VENDOR_ID            bigint(20)                      null comment '近期最低供应商ID',
    LATEST_MIN_VENDOR_CODE          varchar(50)                     null comment '近期最低供应商编码',
    LATEST_MIN_VENDOR_NAME          varchar(255)                    null comment '机器最低供应商名称',
    LATEST_MIN_BRAND                varchar(50)                     null comment '近期最低价品牌',
    EXT_WIN_REASON                  text                            null comment '中标原因',
    ORDER_REMARK                    text                            null comment '供应商备注',
    SPECIAL_PAYMENT_REMARK          text                            null comment '特殊付款说明',
    EXT_LEAD_TIME                   int                             null comment '供货周期',
    BUYER_USER_NAME                 varchar(50)                     null comment '采购员账号',
    BUYER_NICKNAME                  varchar(150)                    null comment '采购员昵称',
    APPLY_TYPE                      varchar(20)                     null comment '申请类型(??????????)',
    EXT_WARRANTY_PERIOD             int                             null comment '质保期',
    EXT_PREDICT_PRICE               decimal(24,8)                   null comment '预估单价',
    EXT_PREDICT_AMOUNT              decimal(24,8)                   null comment '预估总价',
    EXT_BUY_TYPE                    varchar(20)                     null comment '购买类型(PR_BUY_TYPE)',
    FIX_PRICE_LINE_STATUS           varchar(20)                     not null comment '审批状态(EXT_SOU_FIX_PRICE_LINE_STATUS)',
    EXT_SOU_FIX_PRICE_LINE_STATUS   char(1)                         default 'N' not null comment '是否关闭',
    HAS_SIGNED_CONTRACT             char(1)                         default 'N' not null comment '是否签订合同',

    CREATED_ID                      bigint                          not null comment '创建人ID',
    CREATED_BY                      varchar(50)                     not null comment '创建人',
    CREATION_DATE                   datetime                        not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)                    not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)                    null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint                          null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)                     null comment '更新人',
    LAST_UPDATE_DATE                datetime                        null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)                    null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)                    null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)                     null comment '租户ID',
    VERSION                         bigint     default 0            null comment '版本号'
) comment '长城定价单物料明细表';

create table scc_npm_sou_fix_price_file (
    FIX_PRICE_FILE_ID               bigint(20)                      not null primary key,
    FIX_PRICE_HEAD_ID               bigint(20)                      not null comment '定价单ID',
    FILE_ID                         bigint(20)                      null comment '文件ID',
    FILE_NAME                       varchar(150)                    null comment '文件名称',

    CREATED_ID                      bigint                          not null comment '创建人ID',
    CREATED_BY                      varchar(50)                     not null comment '创建人',
    CREATION_DATE                   datetime                        not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)                    not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)                    null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint                          null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)                     null comment '更新人',
    LAST_UPDATE_DATE                datetime                        null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)                    null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)                    null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)                     null comment '租户ID',
    VERSION                         bigint     default 0            null comment '版本号'
) comment '长城定价单附件表';

