create table scc_npm_sou_purfix_price_head (
    PUR_FIX_PRICE_HEAD_ID           bigint(20)                      not null primary key,
    FIX_PRICE_STATUS                varchar(20)                     not null comment '单据状态',
    SOU_PROJECT_ID                  bigint(20)                      null comment '寻源单ID',
    SOU_NO                          varchar(50)                     null comment '寻源单号',
    DESIGN_ID                       bigint(20)                      null comment '项目策划方案ID',
    DESIGN_PROJECT_CODE             varchar(50)                     null comment '项目策划方案编码',
    DESIGN_PROJECT_NAME             varchar(255)                    null comment '项目策划方案名称',
    EXECUTE_TIME_FROM               datetime                        null comment '执行时间从',
    EXECUTE_TIME_TO                 datetime                        null comment '执行时间到',
    CAN_SUBMIT                      char(1) default 'N'             not null comment '是否可提交',
    CREATE_USER_ORG_OU_ID           bigint(20)                      null comment '创建人所属公司ID',
    CREATE_USER_ORG_OU_CODE         varchar(50)                     null comment '创建人所属公司编码',
    CREATE_USER_ORG_OU_NAME         varchar(255)                    null comment '创建人所属公司名称',

    CREATED_ID                      bigint                          not null comment '创建人ID',
    CREATED_BY                      varchar(50)                     not null comment '创建人',
    CREATION_DATE                   datetime                        not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)                    not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)                    null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint                          null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)                     null comment '更新人',
    LAST_UPDATE_DATE                datetime                        null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)                    null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)                    null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)                     null comment '租户ID',
    VERSION                         bigint     default 0            null comment '版本号'
) comment '长城集采定价头表';

create table scc_npm_sou_purfix_price_line (
    PUR_FIX_PRICE_LINE_ID           bigint(20)                      not null primary key,
    PUR_FIX_PRICE_HEAD_ID           bigint(20)                      not null comment '定价单ID',
    ROUND                           int                             null comment '轮次',
    ITEM_ID                         bigint(20)                      null comment '物料ID',
    ITEM_CODE                       varchar(80)                     null comment '物料编码',
    ITEM_DESC                       varchar(255)                    null comment '物料名称',
    MODEL                           varchar(255)                    null comment '规格型号',
    UNIT                            varchar(20)                     null comment '单位',
    REQUIRE_QUANTITY                decimal(24,8)                   null comment '需求数量',
    REMARK                          text                            null comment '备注',
    NOTAX_PRICE                     decimal(24,8)                   null comment '未税单价',
    TAX_PRICE                       decimal(24,8)                   null comment '含税单价',
    TAX_KEY                         varchar(30)                     null comment '税率编码',
    TAX_RATE                        decimal(24,8)                   null comment '税率值',
    LEAD_TIME                       int                             null comment '质保期(自然日)',
    VENDOR_ID                       bigint(20)                      null comment '供应商ID',
    VENDOR_CODE                     varchar(50)                     null comment '供应商编码',
    VENDOR_NAME                     varchar(255)                    null comment '供应商名称',
    SOU_PROJECT_ID                  bigint(20)                      null comment '寻源单ID',
    SOU_ITEM_ID                     bigint(20)                      null comment '寻源物料需求ID',
    SOU_ORDER_ID                    bigint(20)                      null comment '寻源报价单ID',
    SOU_ORDER_ITEM_ID               bigint(20)                      null comment '寻源报价明细ID',
    FIX_PRICE_STATUS                varchar(20)                     not null comment '单据状态',

    CREATED_ID                      bigint                          not null comment '创建人ID',
    CREATED_BY                      varchar(50)                     not null comment '创建人',
    CREATION_DATE                   datetime                        not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)                    not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)                    null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint                          null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)                     null comment '更新人',
    LAST_UPDATE_DATE                datetime                        null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)                    null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)                    null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)                     null comment '租户ID',
    VERSION                         bigint     default 0            null comment '版本号'
) comment '长城集采定价明细表';

create table scc_npm_sou_purfix_price_file (
    PUR_FIX_PRICE_FILE_ID           bigint(20)                      not null primary key,
    PUR_FIX_PRICE_HEAD_ID           bigint(20)                      not null comment '定价单ID',
    FILE_ID                         bigint(20)                      null comment '文件ID',
    FILE_NAME                       varchar(150)                    null comment '文件名称',
    SORT_INDEX                      int                             not null comment '排序',

    CREATED_ID                      bigint                          not null comment '创建人ID',
    CREATED_BY                      varchar(50)                     not null comment '创建人',
    CREATION_DATE                   datetime                        not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)                    not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)                    null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint                          null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)                     null comment '更新人',
    LAST_UPDATE_DATE                datetime                        null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)                    null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)                    null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)                     null comment '租户ID',
    VERSION                         bigint     default 0            null comment '版本号'
) comment '长城集采定价附件表';