alter table scc_sou_answer
    add column EXT_SECTOR_CODE VARCHAR(30) NULL DEFAULT NULL COMMENT '板块代码',
    add column EXT_SECTOR_ID BIGINT NULL DEFAULT NULL COMMENT '板块ID',
    add column EXT_SECTOR_NAME varchar(50) NULL DEFAULT NULL COMMENT '板块名称',
    add column EXT_DEPT_ID BIGINT NULL DEFAULT NULL COMMENT '所属部门ID',
    add column EXT_DEPT_NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '所属部门名称',
    add column EXT_DEPT_CODE VARCHAR(20) NULL DEFAULT NULL COMMENT '所属部门代码',
    add column EXT_COMPANY_ID BIGINT NULL DEFAULT NULL COMMENT '所属公司ID',
    add column EXT_COMPANY_NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '所属公司名称',
    add column EXT_COMPANY_CODE VARCHAR(20) NULL DEFAULT NULL COMMENT '所属公司代码';


alter table scc_sou_question
    add column EXT_SECTOR_CODE VARCHAR(30) NULL DEFAULT NULL COMMENT '板块代码',
    add column EXT_SECTOR_ID BIGINT NULL DEFAULT NULL COMMENT '板块ID',
    add column EXT_SECTOR_NAME varchar(50) NULL DEFAULT NULL COMMENT '板块名称',
    add column EXT_DEPT_ID BIGINT NULL DEFAULT NULL COMMENT '所属部门ID',
    add column EXT_DEPT_NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '所属部门名称',
    add column EXT_DEPT_CODE VARCHAR(20) NULL DEFAULT NULL COMMENT '所属部门代码',
    add column EXT_COMPANY_ID BIGINT NULL DEFAULT NULL COMMENT '所属公司ID',
    add column EXT_COMPANY_NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '所属公司名称',
    add column EXT_COMPANY_CODE VARCHAR(20) NULL DEFAULT NULL COMMENT '所属公司代码';