CREATE TABLE IF NOT EXISTS `scc_sou_ch_paa_adjust_att` (
    `ADJUST_ATT_ID` bigint(20) NOT NULL COMMENT '调整申请附件id',
    `ADJUST_ID` bigint(20) DEFAULT NULL COMMENT '调整申请id',
    `FILE_ID` bigint(20) DEFAULT NULL COMMENT '文件id',
    `FILE_NAME` varchar(50) DEFAULT NULL COMMENT '文件名称',
    `REMAKE` varchar(500) DEFAULT NULL COMMENT '备注',
    `CREATED_ID` bigint(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY` varchar(50) NOT NULL COMMENT '创建人',
    `CREATED_FULL_NAME` varchar(50) NOT NULL COMMENT '创建人姓名',
    `CREATION_DATE` datetime NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP` varchar(150) NOT NULL COMMENT '创建人IP',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY` varchar(50) DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE` datetime DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP` varchar(150) DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID` varchar(30) DEFAULT NULL COMMENT '租户ID',
    `VERSION` bigint(20) DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`ADJUST_ATT_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='集采台账-调价申请-调价申请附件';