
ALTER TABLE `scc_npm_sou_fix_price_head`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_sou_ch_design_plan`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_npm_bid_data_submit`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_npm_borrow`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_npm_sou_bid_notice`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称',
    ADD COLUMN `START_BPM_DISCARD_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '废弃 bpm发起人账号',
	ADD COLUMN `START_BPM_DISCARD_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '废弃 bpm发起人名称';
ALTER TABLE `scc_npm_inspect`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称',
    ADD COLUMN `START_BPM_REPORT_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '报告 bpm发起人账号',
	ADD COLUMN `START_BPM_REPORT_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '报告 bpm发起人名称';
ALTER TABLE `scc_npm_sou_ca`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称',
    ADD COLUMN `START_BPM_DISCARD_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '废弃 bpm发起人账号',
	ADD COLUMN `START_BPM_DISCARD_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '废弃 bpm发起人名称';