ALTER TABLE `scc_npm_borrow_attach`
    CHANGE COLUMN `ATTACH_NAME` `ATTACH_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '附件名称' AFTER `ATTACH_ID`,
    CHANGE COLUMN `ATTACH_PATH` `ATTACH_PATH` VARCHAR(500) NULL DEFAULT NULL COMMENT '附件路径' AFTER `ATTACH_NAME`;
