CREATE TABLE IF NOT EXISTS scc_npm_sou_bid_notice (
    bid_notice_id BIGINT(20) NOT NULL COMMENT '中落标通知ID',
    bid_notice_no VARCHAR(50) NULL DEFAULT NULL COMMENT '中/落标通知单号',
	type VARCHAR(20) NULL DEFAULT NULL COMMENT '类型',
	status VARCHAR(50) NULL DEFAULT NULL COMMENT '单据状态',
    ext_org_bu_id BIGINT(20) NULL DEFAULT NULL COMMENT '板块ID',
	ext_org_bu_code VARCHAR(50) NULL DEFAULT NULL COMMENT '板块编码',
	ext_org_bu_name VARCHAR(255) NULL DEFAULT NULL COMMENT '板块名称',
    ext_org_ou_id BIGINT(20) NULL DEFAULT NULL COMMENT '公司ID',
	ext_org_ou_code VARCHAR(50) NULL DEFAULT NULL COMMENT '公司编码',
    ext_org_ou_name VARCHAR(255) NULL DEFAULT NULL COMMENT '公司名称',
    project_id BIGINT(20) NULL DEFAULT NULL COMMENT '项目ID',
    sou_name VARCHAR(100) NULL DEFAULT NULL COMMENT '项目名称',
    sou_no VARCHAR(50) NULL DEFAULT NULL COMMENT '寻源单号',
	sou_type VARCHAR(20) NULL DEFAULT NULL COMMENT '寻源类型',
	ext_project_no VARCHAR(50) NULL DEFAULT NULL COMMENT '招标项目编号',
    demand_department_id VARCHAR(20) NULL DEFAULT NULL COMMENT '需求部门ID',
	demand_department_code VARCHAR(30) NULL DEFAULT NULL COMMENT '需求部门编码',
	demand_department_name VARCHAR(50) NULL DEFAULT NULL COMMENT '需求部门名称',
	demand_user_id VARCHAR(200) NULL DEFAULT NULL COMMENT '需求人id(可多选)',
	demand_user_name VARCHAR(200) NULL DEFAULT NULL COMMENT '需求人工号',
	demand_user_nickname VARCHAR(200) NULL DEFAULT NULL COMMENT '需求人名称',
	ext_tech_principal VARCHAR(50) NULL DEFAULT NULL COMMENT '招标技术负责人',
    ext_tech_phone VARCHAR(50) NULL DEFAULT NULL COMMENT '联系电话',
    remark VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
    original_bid_notice_id BIGINT(20) NULL DEFAULT NULL COMMENT '原中落标通知ID',
    original_bid_notice_no VARCHAR(50) NULL DEFAULT NULL COMMENT '原中/落标通知单号',
    discard_type VARCHAR(50) NULL DEFAULT NULL COMMENT '废弃类型',
    discard_reason VARCHAR(500) NULL DEFAULT NULL COMMENT '废弃原因',
	abandon_reason VARCHAR(500) NULL DEFAULT NULL COMMENT '中/落标废弃原因',
	ca_id BIGINT(20) NULL DEFAULT NULL COMMENT '定/废标申请单ID',
    ca_no VARCHAR(50) NULL DEFAULT NULL COMMENT '定/废标申请单单号',
    start_date DATE NULL DEFAULT NULL COMMENT '生效日期',
    end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
    created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    creation_date DATETIME NOT NULL COMMENT '创建时间',
    created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
    created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
    last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
    last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
    tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
    version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (bid_notice_id)
) COMMENT '中落标通知头表';

CREATE TABLE IF NOT EXISTS scc_npm_sou_bid_notice_detail (
    bid_notice_detail_id BIGINT(20) NOT NULL COMMENT '中/落标通知明细ID',
    bid_notice_id BIGINT(20) NOT NULL COMMENT '中/落标通知ID',
    line_num INT(11) NULL DEFAULT NULL COMMENT '序号',
    vendor_id BIGINT(20) NULL DEFAULT NULL COMMENT '供应商ID',
    vendor_code VARCHAR(50) NULL DEFAULT NULL COMMENT '供应商编码',
    vendor_name VARCHAR(500) NULL DEFAULT NULL COMMENT '供应商名称',
    is_win VARCHAR(10) NULL DEFAULT NULL COMMENT '是否中标',
    win_amount DECIMAL(24,8) NULL DEFAULT NULL COMMENT '中标金额（元）',
    contract_sign_unit VARCHAR(100) NULL DEFAULT NULL COMMENT '合同签署单位',
    contract_period VARCHAR(100) NULL DEFAULT NULL COMMENT '合同周期',
    is_performance_evaluated VARCHAR(10) NULL DEFAULT NULL COMMENT '是否履约评价',
    non_performance_reason VARCHAR(500) NULL DEFAULT NULL COMMENT '不履约评价的原因',
    is_on_site_inspected VARCHAR(10) NULL DEFAULT NULL COMMENT '是否现场考察',
	inspect_id BIGINT(20) NULL DEFAULT NULL COMMENT '现场考察ID',
    notice_attachment_id BIGINT(20) NULL DEFAULT NULL COMMENT '通知书附件ID',
    notice_attachment_name VARCHAR(200) NULL DEFAULT NULL COMMENT '通知书附件名称',
	is_sign VARCHAR(10) NULL DEFAULT NULL COMMENT '是否盖章',
    is_send VARCHAR(10) NULL DEFAULT NULL COMMENT '是否发送',
	send_time DATETIME NULL DEFAULT NULL COMMENT '发送时间',
    start_date DATE NULL DEFAULT NULL COMMENT '生效日期',
    end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
    created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    creation_date DATETIME NOT NULL COMMENT '创建时间',
    created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
    created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
    last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
    last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
    tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
    version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (bid_notice_detail_id)
) COMMENT='中/落标通知明细表';

CREATE TABLE IF NOT EXISTS scc_npm_sou_bid_notice_internal(
	internal_id BIGINT(20) NOT NULL COMMENT '内部通知ID',
	bid_notice_id BIGINT(20) NULL DEFAULT NULL COMMENT '中落标通知ID',
	line_num INT(11) NULL DEFAULT NULL COMMENT '序号',
	ext_org_bu_id BIGINT(20) NULL DEFAULT NULL COMMENT '板块ID',
	ext_org_bu_code VARCHAR(50) NULL DEFAULT NULL COMMENT '板块编码',
	ext_org_bu_name VARCHAR(255) NULL DEFAULT NULL COMMENT '板块名称',
    ext_org_ou_id BIGINT(20) NULL DEFAULT NULL COMMENT '公司ID',
	ext_org_ou_code VARCHAR(50) NULL DEFAULT NULL COMMENT '公司编码',
    ext_org_ou_name VARCHAR(255) NULL DEFAULT NULL COMMENT '公司名称',
	demand_department_id VARCHAR(20) NULL DEFAULT NULL COMMENT '需求部门ID',
	demand_department_code VARCHAR(30) NULL DEFAULT NULL COMMENT '需求部门编码',
	demand_department_name VARCHAR(50) NULL DEFAULT NULL COMMENT '需求部门名称',
	attachment_id BIGINT(20) NULL DEFAULT NULL COMMENT '通知书附件ID',
	attachment_name VARCHAR(200) NULL DEFAULT NULL COMMENT '通知书附件名称',
	is_sign VARCHAR(10) NULL DEFAULT NULL COMMENT '是否盖章',
	is_send VARCHAR(10) NULL DEFAULT NULL COMMENT '是否发送',
	send_time DATETIME NULL DEFAULT NULL COMMENT '发送时间',
	start_date DATE NULL DEFAULT NULL COMMENT '生效日期',
	end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
	created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
	created_by VARCHAR(50) NOT NULL COMMENT '创建人',
	creation_date DATETIME NOT NULL COMMENT '创建时间',
	created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
	created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
	last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
	last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
	last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
	last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
	last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
	tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
	version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	PRIMARY KEY (internal_id)
) COMMENT='内部通知书表';