create table scc_npm_sou_expert (
    EXPERT_ID                       bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_ID                 bigint              not null comment '专家申请ID',
    EXPERT_APPLY_NO                 varchar(50)         not null comment '专家申请编码',
    EXPERT_LEVEL                    varchar(30)         not null comment '专家等级',
    EXPERT_USER_ID                  bigint              null comment '专家ID',
    EXPERT_USER_CODE                varchar(50)         null comment '专家工号',
    EXPERT_USERNAME                 varchar(50)         null comment '专家账号',
    EXPERT_FULL_NAME                varchar(150)        null comment '专家昵称',
    JOB_STATUS                      varchar(10)         null comment '在职状态',
    APPLY_ID_FULL_PATH              varchar(80)         not null comment '申请单ID记录',
    HAS_QUITE                       char(1) default 'N' not null comment '是否已退出',
    HAS_FROZEN                      char(1) default 'N' not null comment '是否已冻结',
    QUITE_REASON                    text                null comment '退出原因',
    FROZEN_STATUS                   varchar(20)         null comment '冻结状态',
    FROZEN_REASON                   text                null comment '冻结原因',
    FROZEN_REJECT_REASON            text                null comment '拒绝说明',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家库';

create table scc_npm_sou_expert_apply (
    EXPERT_APPLY_ID                 bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_NO                 varchar(50)         not null comment '专家申请编号',
    APPLY_FROM_TYPE                 varchar(30)         not null comment '数据来源',
    APPLY_BY_ID                     bigint              null comment '申请人ID',
    APPLY_BY                        varchar(50)         null comment '申请人账号',
    APPLY_BY_CODE                   varchar(40)         null comment '申请人工号',
    APPLY_BY_NICKNAME               varchar(150)        null comment '申请人昵称',
    APPLY_TIME                      datetime            null comment '申请时间',
    APPLY_STATUS                    varchar(30)         null comment '申请状态',
    HAS_SUBMIT                      char(1) default 'N' not null comment '是否已提交',
    HIGHEST_DEGREE                  varchar(30)         null comment '最高学历',
    sex                             varchar(10)         null comment '性别',
    ORG_OU_ID                       bigint              null comment '所属公司ID',
    ORG_OU_CODE                     varchar(50)         null comment '所属公司编码',
    ORG_OU_NAME                     varchar(150)        null comment '所属公司名称',
    DEPARTMENT_ID                   varchar(30)         null comment '申请部门ID',
    DEPARTMENT_NAME                 varchar(150)        null comment '申请部门名称',
    JOB                             varchar(30)         null comment '职务',
    JOB_RANK                        varchar(30)         null comment '职务职级(序列等级)',
    EXPERT_LEVEL                    varchar(30)         null comment '专家等级',
    JOB_STATUS                      varchar(10)         null comment '在职状态',
    PHONE                           varchar(50)         null comment '手机号码',
    HIRE_DATE                       date                null comment '入职时间',
    APPLY_LEVEL                     varchar(30)         null comment '申请等级',
    FROM_APPLY_ID                   varchar(80)         null comment '用于专家升级时记录来源申请单号',
    GREEN_REASON                    text                null comment '绿色通道原因',
    UPGRADE_REASON                  text                null comment '升级申请原因',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家申请';

create table scc_npm_sou_expert_category (
    EXPERT_CATEGORY_ID              bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_ID                 bigint              not null comment '专家申请ID',
    CATEGORY_ID                     bigint              null comment '品类ID',
    CATEGORY_CODE                   varchar(80)         null comment '品类编码',
    CATEGORY_NAME                   varchar(150)        null comment '品类名称',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家申请适用品类';

create table scc_npm_sou_expert_apply_edu (
    EXPERT_EDUCATION_ID             bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_ID                 bigint              not null comment '专家申请ID',
    EDUCATION                       varchar(30)         null comment '学历',
    STUDY_COLLEGE                   varchar(255)        null comment '就读院校',
    FULL_TIME_STUDY                 char(1) default 'Y' null comment '是否全日制',
    STUDY_DATE_FROM                 date                null comment '就读时间从',
    STUDY_DATE_TO                   date                null comment '就读时间到',
    MAJOR                           varchar(150)        null comment '主修专业',
    DEGREE_CERTIFY_DOC_ID           bigint              null comment '学位证书-文件ID',
    DEGREE_CERTIFY_FILE_NAME        varchar(150)        null comment '学位证书-文件名称',
    GRADUATION_CERTIFY_DOC_ID       bigint              null comment '毕业证书-文件ID',
    GRADUATION_CERTIFY_FILE_NAME    varchar(150)        null comment '毕业证书-文件名称',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家申请学历';

create table scc_npm_sou_expert_org (
    EXPERT_ORG_ID                   bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_ID                 bigint              not null comment '专家申请ID',
    ORG_ID                          bigint              null comment '组织ID',
    ORG_CODE                        varchar(50)         null comment '组织编码',
    ORG_NAME                        varchar(150)        null comment '组织名称',
    FULL_PATH_ID                    varchar(150)        null comment '组织全路径ID',
    FULL_PATH_NAME                  varchar(300)        null comment '组织全路径名称',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家申请适用组织';

create table scc_npm_sou_expert_work (
    EXPERT_WORK_ID                  bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_ID                 bigint              not null comment '专家申请ID',
    WORK_UNIT                       varchar(255)        null comment '工作单位',
    JOB                             varchar(150)        null comment '职务',
    JOB_RANK                        varchar(30)         null comment '职务职级(序列等级)',
    ENTRY_DATE                      date                null comment '入职时间',
    QUIT_DATE                       date                null comment '离职时间',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家申请工作经历';

create table scc_npm_sou_expert_work_relate (
    EXPERT_WORK_RELATE_ID           bigint              not null comment 'ID' primary key,
    EXPERT_APPLY_ID                 bigint              not null comment '专家申请ID',
    RELATIVE_NAME                   varchar(50)         null comment '亲属名称',
    RELATIVE_TYPE                   varchar(30)         null comment '亲属关系',
    WORK_UNIT                       varchar(255)        null comment '工作单位',
    JOB                             varchar(150)        null comment '职务',
    ENTRY_DATE                      date                null comment '入职时间',
    QUIT_DATE                       date                null comment '离职时间',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '专家申请亲属工作经历';