CREATE TABLE IF NOT EXISTS scc_npm_sou_ca (
    ca_id BIGINT(20) NOT NULL COMMENT '定/废标申请单ID',
    ca_no VARCHAR(50) NULL DEFAULT NULL COMMENT '定/废标申请单单号',
    type VARCHAR(50) NULL DEFAULT NULL COMMENT '类型',
    original_ca_id BIGINT(20) NULL DEFAULT NULL COMMENT '原定标申请ID',
    original_ca_no VARCHAR(50) NULL DEFAULT NULL COMMENT '原定标申请单号',
	ext_org_bu_id BIGINT(20) NULL DEFAULT NULL COMMENT '板块ID',
	ext_org_bu_code VARCHAR(50) NULL DEFAULT NULL COMMENT '板块编码',
	ext_org_bu_name VARCHAR(255) NULL DEFAULT NULL COMMENT '板块名称',
    ext_org_ou_id BIGINT(20) NULL DEFAULT NULL COMMENT '公司ID',
	ext_org_ou_code VARCHAR(50) NULL DEFAULT NULL COMMENT '公司编码',
    ext_org_ou_name VARCHAR(255) NULL DEFAULT NULL COMMENT '公司名称',
    project_id BIGINT(20) NULL DEFAULT NULL COMMENT '项目ID',
    sou_name VARCHAR(100) NULL DEFAULT NULL COMMENT '寻源名称',
    sou_no VARCHAR(50) NULL DEFAULT NULL COMMENT '寻源单号',
	sou_type VARCHAR(20) NULL DEFAULT NULL COMMENT '寻源类型',
	ext_project_no VARCHAR(50) NULL DEFAULT NULL COMMENT '招标项目编号',
    status VARCHAR(20) NULL DEFAULT NULL COMMENT '单据状态',
    discard_description VARCHAR(500) NULL DEFAULT NULL COMMENT '废弃说明',
    demand_department_id VARCHAR(20) NULL DEFAULT NULL COMMENT '需求部门ID',
	demand_department_code VARCHAR(30) NULL DEFAULT NULL COMMENT '需求部门编码',
	demand_department_name VARCHAR(50) NULL DEFAULT NULL COMMENT '需求部门名称',
	demand_user_id VARCHAR(200) NULL DEFAULT NULL COMMENT '需求人id(可多选)',
	demand_user_name VARCHAR(200) NULL DEFAULT NULL COMMENT '需求人工号',
	demand_user_nickname VARCHAR(200) NULL DEFAULT NULL COMMENT '需求人名称',
    warranty_period VARCHAR(20) NULL DEFAULT NULL COMMENT '质保期',
	ext_budget DECIMAL(24,6) NULL DEFAULT NULL COMMENT '预算',
    time_limit VARCHAR(50) NULL DEFAULT NULL COMMENT '工期/交货期要求',
    publish_time DATETIME NULL DEFAULT NULL COMMENT '发标时间',
    bus_end_time DATETIME NULL DEFAULT NULL COMMENT '收标时间',
    tech_evaluation_time DATETIME NULL DEFAULT NULL COMMENT '评标结束',
    price_opening_time DATETIME NULL DEFAULT NULL COMMENT '开价格标时间',
    project_overview_and_bid_scope VARCHAR(2000) NULL DEFAULT NULL COMMENT '项目概况与招标范围',
    payment_requirements VARCHAR(500) NULL DEFAULT NULL COMMENT '付款要求',
    remark VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
	ext_category_id BIGINT(20) NULL DEFAULT NULL COMMENT '品类ID',
	ext_category_code VARCHAR(50) NULL DEFAULT NULL COMMENT '品类编码',
	ext_category_name VARCHAR(100) NULL DEFAULT NULL COMMENT '品类名称',
	if_write VARCHAR(50) NULL DEFAULT NULL COMMENT '是否填写',
	tech_weight DECIMAL(24,6) NULL DEFAULT NULL COMMENT '技术权重',
	abandon_desc VARCHAR(500) NULL DEFAULT NULL COMMENT '废弃定标说明',
    start_date DATE NULL DEFAULT NULL COMMENT '生效日期',
    end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
    created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    creation_date DATETIME NOT NULL COMMENT '创建时间',
    created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
    created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
    last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
    last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
    tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
    version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	contract_operator_user_id BIGINT(20) NULL DEFAULT NULL COMMENT '合同经办人ID',
	contract_operator_username VARCHAR(50) NULL DEFAULT NULL COMMENT '合同经办人账号',
	contract_operator_nickname VARCHAR(100) NULL DEFAULT NULL COMMENT '合同经办人名称',
	ext_score_rule VARCHAR(20) NULL DEFAULT NULL COMMENT '评分规则（字典）',
	ext_sou_process VARCHAR(20) NULL DEFAULT NULL COMMENT '招标流程',
    PRIMARY KEY (ca_id)
) COMMENT='定标申请';

CREATE TABLE IF NOT EXISTS scc_npm_sou_ca_order(
	ca_order_id BIGINT(20) NOT NULL COMMENT '主键ID',
	line_num INT(11) NULL DEFAULT NULL COMMENT '序号',
    ca_id BIGINT(20) NULL DEFAULT NULL COMMENT '定标申请ID',
    vendor_id BIGINT(20) NULL DEFAULT NULL COMMENT '供应商ID',
    vendor_code VARCHAR(50) NULL DEFAULT NULL COMMENT '供应商编码',
    vendor_name VARCHAR(500) NULL DEFAULT NULL COMMENT '供应商名称',
	ext_vendor_attr VARCHAR(50) NULL DEFAULT NULL COMMENT '供应商属性',
	order_status VARCHAR(20) NULL DEFAULT NULL COMMENT '投标状态',
	tender_package_name VARCHAR(500) NULL DEFAULT NULL COMMENT '投标包名',
	withdraw_reason VARCHAR(300) NULL DEFAULT NULL COMMENT '不参与原因',
	reject_reason VARCHAR(300) NULL DEFAULT NULL COMMENT '废标原因',
	start_date DATE NULL DEFAULT NULL COMMENT '生效日期',
	end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
	created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
	created_by VARCHAR(50) NOT NULL COMMENT '创建人',
	creation_date DATETIME NOT NULL COMMENT '创建时间',
	created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
	created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
	last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
	last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
	last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
	last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
	last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
	tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
	version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	PRIMARY KEY (ca_order_id)
) COMMENT='投标供应商';


CREATE TABLE IF NOT EXISTS scc_npm_sou_ca_selection_result (
    selection_result_id BIGINT(20) NOT NULL COMMENT '供应商选定结果ID',
    line_num INT(11) NULL DEFAULT NULL COMMENT '序号',
    ca_id BIGINT(20) NULL DEFAULT NULL COMMENT '定标申请ID',
    vendor_id BIGINT(20) NULL DEFAULT NULL COMMENT '供应商ID',
    vendor_code VARCHAR(50) NULL DEFAULT NULL COMMENT '供应商编码',
    vendor_name VARCHAR(500) NULL DEFAULT NULL COMMENT '供应商名称',
    is_win VARCHAR(10) NULL DEFAULT NULL COMMENT '是否中标',
    win_range VARCHAR(100) NULL DEFAULT NULL COMMENT '中标范围',
    win_reason VARCHAR(200) NULL DEFAULT NULL COMMENT '中/落标原因',
	order_item_id BIGINT(20) NULL DEFAULT NULL COMMENT '报价行ID',
	order_id BIGINT(20) NULL DEFAULT NULL COMMENT '报价单ID',
    start_date DATE NULL DEFAULT NULL COMMENT '生效日期',
    end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
    created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    creation_date DATETIME NOT NULL COMMENT '创建时间',
    created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
    created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
    last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
    last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
    tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
    version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (selection_result_id)
) COMMENT='供应商选定结果表';


CREATE TABLE IF NOT EXISTS scc_npm_sou_ca_supplier (
    ca_supplier_id BIGINT(20) NOT NULL COMMENT '供应商总体情况ID',
    line_num INT NULL COMMENT '序号',
    ca_id BIGINT(20) NULL COMMENT '定标申请ID',
    vendor_id BIGINT(20) NULL DEFAULT NULL COMMENT '供应商ID',
    vendor_code VARCHAR(50) NULL DEFAULT NULL COMMENT '供应商编码',
    vendor_name VARCHAR(500) NULL DEFAULT NULL COMMENT '供应商名称',
    bid_total_price DECIMAL(24,8) NULL COMMENT '投标含税总价（万元）',
	tech_score DECIMAL(6,3) NULL DEFAULT NULL COMMENT '技术得分',
	price_score DECIMAL(6,3) NULL DEFAULT NULL COMMENT '价格得分',
    composite_score DECIMAL(6,3) NULL DEFAULT NULL COMMENT '综合得分',
    comprehensive_evaluation VARCHAR(50) NULL COMMENT '综合评定',
	order_item_id BIGINT(20) NULL DEFAULT NULL NULL COMMENT '报价行ID',
	order_id BIGINT(20) NULL DEFAULT NULL NULL COMMENT '报价单ID',
    start_date DATE NULL DEFAULT NULL NULL COMMENT '生效日期',
    end_date DATE NULL DEFAULT NULL COMMENT '失效日期',
    created_id BIGINT(20) NOT NULL COMMENT '创建人ID',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    creation_date DATETIME NOT NULL COMMENT '创建时间',
    created_by_ip VARCHAR(150) NOT NULL COMMENT '创建人IP',
    created_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名',
    last_updated_id BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
    last_updated_by VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    last_update_date DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
    last_updated_by_ip VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP',
    last_updated_full_name VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名',
    tenant_id VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID',
    version BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (ca_supplier_id)
) COMMENT='供应商总体情况';


