ALTER TABLE scc_npm_sou_expert ADD COLUMN BU_CODE VARCHAR(50) COMMENT '板块编码';
ALTER TABLE scc_npm_sou_expert ADD COLUMN BU_NAME VARCHAR(50) COMMENT '板块名称';
ALTER TABLE scc_npm_sou_expert ADD COLUMN BU_ID bigint COMMENT '板块ID';