CREATE TABLE IF NOT EXISTS scc_npm_sou_answer_vendor (
	answer_vendor_id BIGINT(20) NOT NULL COMMENT '主键ID',
	answer_id BIGINT(20) NOT NULL COMMENT '澄清ID',
	line_num INT(11) NULL DEFAULT NULL COMMENT '序号',
	vendor_id BIGINT(20) NULL DEFAULT NULL COMMENT '供应商ID',
    vendor_code VARCHAR(50) NULL DEFAULT NULL COMMENT '供应商编码',
    vendor_name VARCHAR(500) NULL DEFAULT NULL COMMENT '供应商名称',
	if_read VARCHAR(20) NULL DEFAULT NULL COMMENT '是否已查阅',
	read_time DATETIME NULL DEFAULT NULL COMMENT '查询时间',
	if_replay VARCHAR(20) NULL DEFAULT NULL COMMENT '是否已回复',
	last_replay_time DATETIME NULL DEFAULT NULL COMMENT '最新回复时间',
	confirm_status VARCHAR(20) NULL DEFAULT NULL COMMENT '确认状态',
	replay_id  BIGINT(20) NULL DEFAULT NULL COMMENT '最新回复id',
	CREATED_ID BIGINT(20) NOT NULL COMMENT '创建人ID',
	CREATED_BY VARCHAR(50) NOT NULL COMMENT '创建人' ,
	CREATION_DATE DATETIME NOT NULL COMMENT '创建时间',
	CREATED_BY_IP VARCHAR(150) NOT NULL COMMENT '创建人IP' ,
	CREATED_FULL_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' ,
	LAST_UPDATED_ID BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
	LAST_UPDATED_BY VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' ,
	LAST_UPDATE_DATE DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
	LAST_UPDATED_BY_IP VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' ,
	LAST_UPDATED_FULL_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' ,
	TENANT_ID VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' ,
	VERSION BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	PRIMARY KEY (answer_vendor_id) USING BTREE
)
COMMENT='供应商-澄清供应商列表';


CREATE TABLE IF NOT EXISTS scc_npm_sou_replay (
	replay_id  BIGINT(20) NOT NULL COMMENT '回复id',
	answer_vendor_id BIGINT(20) NULL DEFAULT NULL COMMENT '主键ID',
	answer_id BIGINT(20) NULL DEFAULT NULL COMMENT '主键ID',
	replay_content VARCHAR(255) NULL DEFAULT NULL COMMENT '回复内容',
	CREATED_ID BIGINT(20) NOT NULL COMMENT '创建人ID',
	CREATED_BY VARCHAR(50) NOT NULL COMMENT '创建人' ,
	CREATION_DATE DATETIME NOT NULL COMMENT '创建时间',
	CREATED_BY_IP VARCHAR(150) NOT NULL COMMENT '创建人IP' ,
	CREATED_FULL_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' ,
	LAST_UPDATED_ID BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
	LAST_UPDATED_BY VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' ,
	LAST_UPDATE_DATE DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
	LAST_UPDATED_BY_IP VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' ,
	LAST_UPDATED_FULL_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' ,
	TENANT_ID VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' ,
	VERSION BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	PRIMARY KEY (replay_id) USING BTREE
)
COMMENT='供应商-质疑澄清回复表';

CREATE TABLE IF NOT EXISTS scc_npm_sou_replay_file (
	replay_file_id  BIGINT(20) NOT NULL COMMENT '回复附件ID',
	replay_id  BIGINT(20) NULL DEFAULT NULL COMMENT '回复id',
	replay_time DATETIME NULL DEFAULT NULL COMMENT '回复时间',
	remark VARCHAR(255) NULL DEFAULT NULL COMMENT '备注',
	file_id BIGINT(20) NULL DEFAULT NULL COMMENT '附件ID',
	file_name VARCHAR(255) NULL DEFAULT NULL COMMENT '附件名称',
	sign_status VARCHAR(20) NULL DEFAULT NULL COMMENT '签署状态',
	sign_time DATETIME NULL DEFAULT NULL COMMENT '签署时间',
	is_delete VARCHAR(20) NULL DEFAULT 'N' COMMENT '是否逻辑删除',
	CREATED_ID BIGINT(20) NOT NULL COMMENT '创建人ID',
	CREATED_BY VARCHAR(50) NOT NULL COMMENT '创建人' ,
	CREATION_DATE DATETIME NOT NULL COMMENT '创建时间',
	CREATED_BY_IP VARCHAR(150) NOT NULL COMMENT '创建人IP' ,
	CREATED_FULL_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人姓名' ,
	LAST_UPDATED_ID BIGINT(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
	LAST_UPDATED_BY VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人' ,
	LAST_UPDATE_DATE DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
	LAST_UPDATED_BY_IP VARCHAR(150) NULL DEFAULT NULL COMMENT '最后更新人IP' ,
	LAST_UPDATED_FULL_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '最后更新人姓名' ,
	TENANT_ID VARCHAR(30) NULL DEFAULT NULL COMMENT '租户ID' ,
	VERSION BIGINT(20) NULL DEFAULT '0' COMMENT '版本号',
	PRIMARY KEY (replay_file_id) USING BTREE
)
COMMENT='供应商-质疑澄清回复附件表';