<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-biz</artifactId>
        <groupId>com.midea</groupId>
        <version>1.0-russia-PROJECT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloud-biz-feign-pj</artifactId>
    <version>1.0-russia-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <bpmp-price.version>1.0.10</bpmp-price.version>
        <bpmp-partner.version>1.0.1</bpmp-partner.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-api-pj</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-feign-extend</artifactId>
            <version>${srm-project.version}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.mideacloud</groupId>-->
<!--            <artifactId>price-client</artifactId>-->
<!--            <version>${bpmp-price.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>com.mideacloud</groupId>-->
<!--                    <artifactId>mideacloud-common-base</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.mideacloud</groupId>-->
<!--            <artifactId>partner-client</artifactId>-->
<!--            <version>${bpmp-partner.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>com.baomidou</groupId>-->
<!--                    <artifactId>mybatis-plus-extension</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.baomidou</groupId>-->
<!--                    <artifactId>mybatis-plus-core</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.meicloud.meida</groupId>-->
<!--                    <artifactId>meida-common</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.mideacloud</groupId>-->
<!--                    <artifactId>mideacloud-common-objectx</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.midea</groupId>-->
<!--            <artifactId>third-starter-extend</artifactId>-->
<!--            <version>${srm-project.version}</version>-->
<!--            <exclusions>-->
<!--                -->
<!--            </exclusions>-->
<!--        </dependency>-->
    </dependencies>
</project>