bpmp.redis.database=9

#mysql-common
bpmp.db.host=10.168.130.234
#bpmp.db.host=127.0.0.1
bpmp.db.port=3306
bpmp.db.username=bpmp_dev
bpmp.db.password=ENC(TWniU3xF9Ly2ZJqEFpUQ7Q==)

#mysql-database-name
bpmp.db.ide.schema=${global.mysqldb.prefix}bpmp_lcdp_rt
bpmp.db.base.schema=${global.mysqldb.prefix}bpmp_base
bpmp.db.material.schema=${global.mysqldb.prefix}bpmp_material
bpmp.db.order.schema=${global.mysqldb.prefix}bpmp_order
bpmp.db.price.schema=${global.mysqldb.prefix}bpmp_price
bpmp.db.inventory.schema=${global.mysqldb.prefix}bpmp_inventory
bpmp.db.trader.schema=${global.mysqldb.prefix}bpmp_trader
bpmp.db.delivery.schema=${global.mysqldb.prefix}bpmp_delivery

#????
#??BPMP
bpmp.audit.app-code=BPMP
#??e7e7fb5463c411eda453020017000b7b
bpmp.audit.app-secret=e7e7fb5463c411eda453020017000b7b

#xxl
bpmp.xxljob.appname=${spring.application.name}-UAT


#?????????host????????---start
#ide runtime
bpmp.db.ide.host=${bpmp.db.host}
bpmp.db.ide.port=${bpmp.db.port}
bpmp.db.ide.username=${bpmp.db.username}
bpmp.db.ide.password=${bpmp.db.password}

#base
bpmp.db.base.host=${bpmp.db.host}
bpmp.db.base.port=${bpmp.db.port}
bpmp.db.base.username=${bpmp.db.username}
bpmp.db.base.password=${bpmp.db.password}

#material
bpmp.db.material.host=${bpmp.db.host}
bpmp.db.material.port=${bpmp.db.port}
bpmp.db.material.username=${bpmp.db.username}
bpmp.db.material.password=${bpmp.db.password}

#order
bpmp.db.order.host=${bpmp.db.host}
bpmp.db.order.port=${bpmp.db.port}
bpmp.db.order.username=${bpmp.db.username}
bpmp.db.order.password=${bpmp.db.password}

#price
bpmp.db.price.host=${bpmp.db.host}
bpmp.db.price.port=${bpmp.db.port}
bpmp.db.price.username=${bpmp.db.username}
bpmp.db.price.password=${bpmp.db.password}

#inventory
bpmp.db.inventory.host=${bpmp.db.host}
bpmp.db.inventory.port=${bpmp.db.port}
bpmp.db.inventory.username=${bpmp.db.username}
bpmp.db.inventory.password=${bpmp.db.password}

#trader
bpmp.db.trader.host=${bpmp.db.host}
bpmp.db.trader.port=${bpmp.db.port}
bpmp.db.trader.username=${bpmp.db.username}
bpmp.db.trader.password=${bpmp.db.password}

#delivery
bpmp.db.delivery.host=${bpmp.db.host}
bpmp.db.delivery.port=${bpmp.db.port}
bpmp.db.delivery.username=${bpmp.db.username}
bpmp.db.delivery.password=${bpmp.db.password}
#?????????host????????---end

#jdbc????
bpmp.jdbc.connection.params=${global.jdbc.connection.params}
# ??
bpmp.flyway.enabled=true
spring.flyway.baselineVersion.delivery=1
