DELETE
FROM scc_base_quicksearch_config
WHERE NAME = 'pr_requirement_head';

INSERT INTO scc_base_quicksearch_config (QUICKSEARCH_CONFIG_ID, NAME, QUERY_DATASOURCE, QUERY_MODULE, QUERY_LANGUAGE_TYPE, QUERY_MATCH_OPERATOR, QUERY_TABLE, QUERY_MAX_SIZE, QUERY_MODE, CODE_ATTR, VALUE_ATTR, QUERY_LANGUAGE, QUERY_LANGUAGE_CUSTOM, DIALOG_ENABLED, DIALOG_QUERY_TYPE, DIALOG_QUERY_TABLE, DIALOG_QUERY_MAX_SIZE, DIALOG_QUERY_LANGUAGE, DIALOG_QUERY_LANGUAGE_CUSTOM, DESCRIPTION, SELECT_MODE, REFLECT_INPUT_CLASS_NAME, REFLECT_CLASS_NAME, REFLECT_INPUT_METHOD_NAME, REFLECT_METHOD_NAME, REFLECT_INPUT_PROPERTY_NAME, REFLECT_PROPERTY_NAME, SELECT_INPUT_MODE, HTTP_URL, INPUT_HTTP_URL, COMPANY_VIEW_FLAG, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION) VALUES (445679935219712, 'pr_requirement_head', null, 'SUPCOOPERATE_READ', null, 'allMatch', 'scc_pr_requirement_head', 15, null, null, 'REQUIREMENT_HEAD_NUM', 'SELECT t.*
FROM scc_pr_requirement_head t
         LEFT JOIN scc_npm_pr_require_head b ON t.REQUIREMENT_HEAD_ID = b.REQUIREMENT_HEAD_ID
WHERE b.HAS_SEND_SOU_PROFILE = \'N\'', null, null, null, null, null, 'SELECT t.*
FROM scc_pr_requirement_head t
         LEFT JOIN scc_npm_pr_require_head b ON t.REQUIREMENT_HEAD_ID = b.REQUIREMENT_HEAD_ID
WHERE b.HAS_SEND_SOU_PROFILE = \'N\'', null, '', null, '', '', '', '', '', '', null, '', '', 'Y', 8123195817787648, 'super', '2023-10-20 14:33:41', '10.74.159.45', '超级管理员', 8123195817787648, 'super', '2023-10-23 09:54:41', '10.254.103.59', '超级管理员', null, 0);
