-- 计划取消（单据编号）
INSERT INTO scc_base_seq_definition (SEQUENCE_ID, SEQUENCE_NAME, SEQUENCE_CODE, LENGTH, PREFIX, INITIAL_VALUE, CURRENT_VALUE, GRANULAR1, GRANULAR2, GRANULAR3, GRANULAR4, GRANULAR5, GRANULAR6, GRANULAR7, GRANULAR8, GRANULAR9, GRANULAR10, GRANULAR11, GRANULAR12, GRANULAR13, GRANULAR14, GRANULAR15, GRANULAR16, GRANULAR17, GRANULAR18, GRANULAR19, GRANULAR20, SCOPE_DEFINITION, SEQUENCE_NUM_RESET, START_DATE, END_DATE, OFFSET, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION)
VALUES (392217135419393, '招标计划-取消单据', 'SEQ_PR_REQ_SOU_CANCEL', 5, 'C', 0, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '[@df_prefix][@df_date_yyyyMMdd][@df_seq]', null, '2022-12-28 00:00:00', null, null, 8123195817787648, 'yangkn', '2022-12-22 11:12:18', '10.18.4.154', '杨明', 8123195817787648, 'super', '2023-09-21 17:57:48', '10.26.34.192', '超级管理员', null, 0);

insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000100,
     'PR_SOU_PROJECT_PLAN_TYPE', '招标计划 - 项目计划状态', '招标计划 - 项目计划状态', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');

insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000101,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_PROJECT_PLAN_TYPE' and LANGUAGE = 'zh_CN'),
    'NORMAL',      '正常',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');

insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000102,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_PROJECT_PLAN_TYPE' and LANGUAGE = 'zh_CN'),
    'FINISH',      '完结',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');

insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000103,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_PROJECT_PLAN_TYPE' and LANGUAGE = 'zh_CN'),
    'CANCEL',      '取消',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');


-- 新增一个基于mql的采购申请审批流
delete from srm_cbpm_template_header where TEMPLATE_HEAD_ID = 413974876491788;
INSERT INTO srm_cbpm_template_header (TEMPLATE_HEAD_ID, MODEL_ID, TEMPLATE_ID, TEMPLATE_CODE, DESCRIPTION, PENDING_APPROVE_URL, FEIGN_CLIENT, BUSSINESS_CLASS, START_DATE_ACTIVE, END_DATE_ACTIVE, LANGUAGE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, DELETE_FLAG, ENABLE_FLAG, ATTRIBUTE_CATEGORY, ATTRIBUTE1, INTEGRATION_MODE, BUSINESS_NAME, TABLE_URL)
VALUES (413974876491788, 'MQL_PR_SOU_REQUIREMENT_INIT', null, 'MQL_PR_SOU_REQUIREMENT_INIT', null, '/', 'com.midea.cloud.srm.feign.supcooperate.SupcooperateClient', 'com.midea.cloud.srm.supcooperate.ext.requirement.souplan.flow.PrSouRequirementFlowServiceImpl', null, null, '', 8123195817787648, 'super', '2023-04-24 10:17:15', '10.18.4.154', '超级管理员', 8123195817787648, 'super', '2023-04-24 10:17:58', '10.18.4.154', '超级管理员', null, 0, 0, 'N', null, null, 'Push', '招标计划立项审批', '');

-- 新增一个取消单的审批流
delete from srm_cbpm_template_header where TEMPLATE_HEAD_ID = 413974876491789;
INSERT INTO srm_cbpm_template_header (TEMPLATE_HEAD_ID, MODEL_ID, TEMPLATE_ID, TEMPLATE_CODE, DESCRIPTION, PENDING_APPROVE_URL, FEIGN_CLIENT, BUSSINESS_CLASS, START_DATE_ACTIVE, END_DATE_ACTIVE, LANGUAGE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, DELETE_FLAG, ENABLE_FLAG, ATTRIBUTE_CATEGORY, ATTRIBUTE1, INTEGRATION_MODE, BUSINESS_NAME, TABLE_URL)
VALUES (413974876491789, 'MQL_PR_SOU_REQ_CANCEL_INIT', null, 'MQL_PR_SOU_REQ_CANCEL_INIT', null, '/', 'com.midea.cloud.srm.feign.supcooperate.SupcooperateClient', 'com.midea.cloud.srm.supcooperate.ext.requirement.souplanpool.flow.PrSouRequirementCancelFlowServiceImpl', null, null, '', 8123195817787648, 'super', '2023-04-24 10:17:15', '10.18.4.154', '超级管理员', 8123195817787648, 'super', '2023-04-24 10:17:58', '10.18.4.154', '超级管理员', null, 0, 0, 'N', null, null, 'Push', '招标计划取消单审批', '');

-- 新增一个变更单的审批流
delete from srm_cbpm_template_header where TEMPLATE_HEAD_ID = 413974876491798;
INSERT INTO srm_cbpm_template_header (TEMPLATE_HEAD_ID, MODEL_ID, TEMPLATE_ID, TEMPLATE_CODE, DESCRIPTION, PENDING_APPROVE_URL, FEIGN_CLIENT, BUSSINESS_CLASS, START_DATE_ACTIVE, END_DATE_ACTIVE, LANGUAGE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, DELETE_FLAG, ENABLE_FLAG, ATTRIBUTE_CATEGORY, ATTRIBUTE1, INTEGRATION_MODE, BUSINESS_NAME, TABLE_URL)
VALUES (413974876491798, 'MQL_PR_SOU_REQUIREMENT_CHANGE', null, 'MQL_PR_SOU_REQUIREMENT_CHANGE', null, '/', 'com.midea.cloud.srm.feign.supcooperate.SupcooperateClient', 'com.midea.cloud.srm.supcooperate.ext.requirement.souplan.flow.PrSouRequirementChangeFlowServiceImpl', null, null, '', 8123195817787648, 'super', '2023-04-24 10:17:15', '10.18.4.154', '超级管理员', 8123195817787648, 'super', '2023-04-24 10:17:58', '10.18.4.154', '超级管理员', null, 0, 0, 'N', null, null, 'Push', '招标计划变更单审批', '');

insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000104,
     'PR_SOU_REQUIREMENT_FROM', '招标计划 - 需求来源', '招标计划 - 需求来源', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');

insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000105,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FROM' and LANGUAGE = 'zh_CN'),
    'YEAR',      '年度',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000106,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FROM' and LANGUAGE = 'zh_CN'),
    'MONTH',      '月度',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000107,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FROM' and LANGUAGE = 'zh_CN'),
    'WITHOUT_PLAN',      '计划外',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000108,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FROM' and LANGUAGE = 'zh_CN'),
    'SPECIAL_SOU',      '特殊招标',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');


insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000109,
     'PR_SOU_REQUIREMENT_FILE_TYPE', '招标计划 - 文件类型', '招标计划 - 文件类型', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');

insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000110,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FILE_TYPE' and LANGUAGE = 'zh_CN'),
    'OTHER',      '其他',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000111,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FILE_TYPE' and LANGUAGE = 'zh_CN'),
    'RESTRICT_VENDOR',      '是否限制供应商',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000112,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_FILE_TYPE' and LANGUAGE = 'zh_CN'),
    'RESTRICT_BRAND',      '是否限制品类',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');


insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000113,
     'PR_SOU_REQUIREMENT_SPECIAL_REASON', '招标计划 - 特殊原因', '招标计划 - 特殊原因', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000114,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_REASON' and LANGUAGE = 'zh_CN'),
    'MONOPOLY',      '垄断',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000115,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_REASON' and LANGUAGE = 'zh_CN'),
    'GOVERNMENT',      '政府定制',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000116,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_REASON' and LANGUAGE = 'zh_CN'),
    'FACTORY_COOP',      '原厂合作',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000117,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_REASON' and LANGUAGE = 'zh_CN'),
    'OTHER',      '其他',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');


insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000118,
     'PR_SOU_REQUIREMENT_SPECIAL_TYPE', '招标计划 - 特殊招标类型', '招标计划 - 特殊招标类型', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000119,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_TYPE' and LANGUAGE = 'zh_CN'),
    'SPECIAL_VENDOR_ONE',      '特定原因使得供应商唯一',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000120,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_TYPE' and LANGUAGE = 'zh_CN'),
    'TIME_URGENT',      '时间紧急',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000121,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SPECIAL_TYPE' and LANGUAGE = 'zh_CN'),
    'OTHER',      '其他',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');



insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000122,
     'PR_SOU_REQUIREMENT_STATUS', '招标计划池 - 需求状态', '招标计划池 - 需求状态', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000123,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_STATUS' and LANGUAGE = 'zh_CN'),
    'EXECUTING',      '计划中',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000124,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_STATUS' and LANGUAGE = 'zh_CN'),
    'FINISH',      '已完成',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000125,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_STATUS' and LANGUAGE = 'zh_CN'),
    'CANCEL',      '已取消',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000149,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_STATUS' and LANGUAGE = 'zh_CN'),
    'PROJECT',      '项目中',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');


insert into scc_base_dict
(DICT_ID, DICT_CODE, DICT_NAME, DESCRIPTION, LANGUAGE, LANGUAGE_NAME,
 CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000126,
     'PR_SOU_REQUIREMENT_SEND_PROFILE_STATUS', '招标计划池 - 招标资料状态', '招标计划池 - 招标资料状态', 'zh_CN', '中文',
     '1',       'admin',    now(),         '127.0.0.1', '1',             'admin',         '127.0.0.1');
insert into scc_base_dict_item
(DICT_ITEM_ID,
 DICT_ID,
 DICT_ITEM_CODE, DICT_ITEM_NAME, ITEM_LANGUAGE, ITEM_LANGUAGE_NAME,
 ACTIVE_DATE, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP,
 LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATED_BY_IP)
values
    (78000000000127,
     (select DICT_ID from scc_base_dict where DICT_CODE = 'PR_SOU_REQUIREMENT_SEND_PROFILE_STATUS' and LANGUAGE = 'zh_CN'),
    'APPROVED',      '已审批',          'zh_CN',       '中文',
            current_date, '1',       'admin',    now(),         '127.0.0.1',
    '1',             'admin',         '127.0.0.1');


-- 项目计划快查
INSERT INTO scc_base_quicksearch_config (QUICKSEARCH_CONFIG_ID, NAME, QUERY_DATASOURCE, QUERY_MODULE, QUERY_LANGUAGE_TYPE, QUERY_MATCH_OPERATOR, QUERY_TABLE, QUERY_MAX_SIZE, QUERY_MODE, CODE_ATTR, VALUE_ATTR, QUERY_LANGUAGE, QUERY_LANGUAGE_CUSTOM, DIALOG_ENABLED, DIALOG_QUERY_TYPE, DIALOG_QUERY_TABLE, DIALOG_QUERY_MAX_SIZE, DIALOG_QUERY_LANGUAGE, DIALOG_QUERY_LANGUAGE_CUSTOM, DESCRIPTION, SELECT_MODE, REFLECT_INPUT_CLASS_NAME, REFLECT_CLASS_NAME, REFLECT_INPUT_METHOD_NAME, REFLECT_METHOD_NAME, REFLECT_INPUT_PROPERTY_NAME, REFLECT_PROPERTY_NAME, SELECT_INPUT_MODE, HTTP_URL, INPUT_HTTP_URL, COMPANY_VIEW_FLAG, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION) VALUES (443698235834368, 'scc_npm_pr_project_plan_query', null, 'SUPCOOPERATE_READ', null, 'allMatch', 'scc_npm_pr_project_plan', 15, null, null, 'PROJECT_PLAN_ID', 'select t.* from scc_npm_pr_project_plan t where 1=1 and t.PLAN_STATUS = ''NORMAL'' and (t.PROJECT_NAME like :query or t.PLAN_NO like :query) order by t.CREATION_DATE desc', null, null, null, null, null, 'select t.* from scc_npm_pr_project_plan t where 1=1 and t.PLAN_STATUS = ''NORMAL''', null, '招标计划-项目计划查询', null, '', '', '', '', '', '', null, '', '', 'N', 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0);

INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967488, 443698235834368, 't', 'PROJECT_PLAN_ID', 'ID', 'BIGINT', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967489, 443698235834368, 't', 'PROJECT_NAME', '项目名称', 'VARCHAR', null, null, 'Y', 'Y', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967490, 443698235834368, 't', 'SCENE_TYPE', '应用场景', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967491, 443698235834368, 't', 'INIT_DATE', '立项时间', 'DATE', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967492, 443698235834368, 't', 'DEPARTMENT_ID', '投资部门ID', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967493, 443698235834368, 't', 'DEPARTMENT_NAME', '投资部门名称', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967494, 443698235834368, 't', 'INIT_AMOUNT', '立项金额', 'DECIMAL', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967495, 443698235834368, 't', 'PLAN_NO', '计划编号', 'VARCHAR', null, null, 'Y', 'Y', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:34', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967496, 443698235834368, 't', 'PLAN_ADDRESS', '投资地点', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967497, 443698235834368, 't', 'PLAN_LEVEL', '项目级别', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967498, 443698235834368, 't', 'PLAN_STATUS', '项目状态', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967499, 443698235834368, 't', 'REQUIREMENT_HEAD_ID', '被引用的招标计划ID', 'BIGINT', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967500, 443698235834368, 't', 'CREATED_ID', '创建人ID', 'BIGINT', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967501, 443698235834368, 't', 'CREATED_BY', '创建人', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967502, 443698235834368, 't', 'CREATION_DATE', '创建时间', 'TIMESTAMP', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967503, 443698235834368, 't', 'CREATED_BY_IP', '创建人IP', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967504, 443698235834368, 't', 'CREATED_FULL_NAME', '创建人姓名', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967505, 443698235834368, 't', 'LAST_UPDATED_ID', '最后更新人ID', 'BIGINT', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967506, 443698235834368, 't', 'LAST_UPDATED_BY', '更新人', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967507, 443698235834368, 't', 'LAST_UPDATE_DATE', '最后更新时间', 'TIMESTAMP', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967508, 443698235834368, 't', 'LAST_UPDATED_BY_IP', '最后更新人IP', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967509, 443698235834368, 't', 'LAST_UPDATED_FULL_NAME', '最后更新人姓名', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967510, 443698235834368, 't', 'TENANT_ID', '租户ID', 'VARCHAR', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);
INSERT INTO scc_base_quicksearch_attr (QUICKSEARCH_ATTR_ID, QUICKSEARCH_ID, ALIAS, ATTR, TITLE, DATA_TYPE, JAVA_TYPE, CODE_LIST, QUERY_ITEM_ENABLED, DISPLAY_ITEM_ENABLED, SEQ, COLUMN_WIDTH, IS_DIALOG_ATTR, ATTR_ORDER, FILEDTYPE, FILEDOPTION, CREATED_ID, CREATED_BY, CREATION_DATE, CREATED_BY_IP, CREATED_FULL_NAME, LAST_UPDATED_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY_IP, LAST_UPDATED_FULL_NAME, TENANT_ID, VERSION, QUERY_MATCH_OPERATOR, COMPONENT_TYPE, COMPONENT_PROPERTY) VALUES (443698235967511, 443698235834368, 't', 'VERSION', '版本号', 'BIGINT', null, null, 'N', 'N', null, null, null, null, null, null, 8123195817787648, 'super', '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, null, '2023-10-09 09:46:35', '10.74.150.65', '超级管理员', null, 0, null, null, null);