###### ies/iet/tdc/audit ######
#mysql-ies/iet/tdc/audit
apaas.db.host=${global.db.host}
apaas.db.port=${global.db.port}
apaas.db.username=${global.db.username}
apaas.db.password=${global.db.password}

# 开启flyway
apaas.flyway.enabled=true

#actuator接口密码
apaas.security.username=admin
apaas.security.password=ZOoM2z0I


#mysql-database-name
apaas.mysqldb.prefix=${global.mysqldb.prefix:}
apaas.db.audit.schema=${apaas.mysqldb.prefix}apaas_audit_log
apaas.db.iet.schema=${apaas.mysqldb.prefix}apaas_iet
apaas.db.tdc.schema=${apaas.mysqldb.prefix}apaas_tdc
apaas.db.ies.schema=${apaas.mysqldb.prefix}apaas_ies
bpm.db.schema=${apaas.mysqldb.prefix}apaas_workflow
mc.db.schema=${apaas.mysqldb.prefix}apaas_message_center
apaas.db.monitor.schema=${bpm.db.schema}

#audit-db
apaas.db.audit.host=${apaas.db.host}
apaas.db.audit.port=${apaas.db.port}
apaas.db.audit.username=${apaas.db.username}
apaas.db.audit.password=${apaas.db.password}

#iet-db
apaas.db.iet.host=${apaas.db.host}
apaas.db.iet.port=${apaas.db.port}
apaas.db.iet.username=${apaas.db.username}
apaas.db.iet.password=${apaas.db.password}

#tdc-db
apaas.db.tdc.host=${apaas.db.host}
apaas.db.tdc.port=${apaas.db.port}
apaas.db.tdc.username=${apaas.db.username}
apaas.db.tdc.password=${apaas.db.password}

#ies-db
apaas.db.ies.host=${apaas.db.host}
apaas.db.ies.port=${apaas.db.port}
apaas.db.ies.username=${apaas.db.username}
apaas.db.ies.password=${apaas.db.password}

#bpm-db
bpm.db.host=${apaas.db.host}
bpm.db.port=${apaas.db.port}
bpm.db.username=${apaas.db.username}
bpm.db.password=${apaas.db.password}

#mc-db
mc.db.host=${bpm.db.host}
mc.db.port=${bpm.db.port}
mc.db.username=${bpm.db.username}
mc.db.password=${bpm.db.password}

#monitor-db
apaas.db.monitor.host=${apaas.db.host}
apaas.db.monitor.port=${apaas.db.port}
apaas.db.monitor.username=${apaas.db.username}
apaas.db.monitor.password=${apaas.db.password}

###### redis ######
apaas.redis.database=5

###### audit/iet/tdc/ies ######
apaas.iam.auth.prefix=${global.iam.register-address}/${iam.auth.application.context}
apaas.iam.upm.prefix=${global.iam.register-address}/${iam.upm.application.context}
apaas.iam.jobs.prefix=${global.iam.register-address}/iam/jobs
#audit-iam
apaas.iam.audit.app-key=fS3aGqfX4kbQ
apaas.iam.audit.app-secret=ekHkVJuRJ1m59enre90tqoF9en0uIDvabXzvJGL2AhpbhQ1z
#audit-es
apaas.es.audit.url=${global.es.url}
apaas.es.audit.accessKey=${global.es.accessKey}
apaas.es.audit.secretKey=${global.es.secretKey}
#audit-rocketmq
apaas.rocketmq.audit.topic=${global.audit.rocketmq.topic}
rocketmq.name-server=${global.rocketmq.name-server}

#tdc-iam
apaas.iam.tdc.app-key=${apaas.iam.audit.app-key}
apaas.iam.tdc.app-secret=${apaas.iam.audit.app-secret}



#################################################################################################################################################
bpm.cas.tenantCode=T000000001
bpm.iam.permission.appcode=mflow
bpm.iam.accessKeyId=yfPvDJ4a1Dpa
bpm.iam.accessKeySecret=MaIHu7FcEByGJvSYEUbBS6vJnz1aGsZPviXMRHolcQcYovlb
bpm.iam.cas.server.url=${global.iam.register-address}
bpm.iam.cas.callback.url=${global.bpm.register-address}/be/authentication/oauth2/callback
bpm.iam.publicKey.url=${apaas.iam.auth.prefix}/login/keys/jwt.verification

bpm.minio.url=${global.minio.url}
bpm.minio.accessKey=${global.minio.accessKey}
bpm.minio.secretKey=${global.minio.secretKey}

spring.flyway.placeholders.srm-root-path=${global.srm.register-address}

#mc
mc.iam.tenantCode=${bpm.cas.tenantCode}
mc.iam.appCode=emcs
mc.iam.accessKey=uOcsGe1NARRz
mc.iam.accessSecret=M59ugZwCU4beDidjcwlgC7S7aIiP9gHgWidJPrE5W6FB0rqO
mc.iam.baseUrl=${global.iam.register-address}

mc.channel.meixin.serverUrl=http://emap-java-mxapps-sit.m-emap-sit:8080
mc.channel.meixin.secret=test
mc.channel.meixin.sysKey=test
mc.channel.meixin.appKey=e212729c
mc.channel.meixin.accessToken=53bc5f37-0975-46e2-a13f-edb90fcc9065
mc.channel.dingtalk.serverUrl=https://mobiledemo.midea.com
mc.channel.corpwechat.serverUrl=https://mobiledemo.midea.com
mc.channel.feishu.serverUrl=https://mobiledemo.midea.com
mc.channel.smsMidea.serverUrl=http://p-sms.midea.com:8001
mc.channel.meixinAlert.serverUrl=https://mapnew5.midea.com
mc.channel.meixinAlert.secret=afbdf5e35f2e2ea0c3c90f0071441e2b
mc.channel.meixinAlert.sysKey=meicloud-alert
mc.channel.meixinAlert.appKey=58031799-ea11-4bb7-b3db-68a9b438766c
mc.channel.meixinAlert.accessToken=cbd39158-12f5-4077-af17-ebf18cf84c7d

mc.http.proxy.enable=false
mc.http.proxy.ip=10.18.4.29
mc.http.proxy.port=9000

mc.inbox.dataArchiving.month=6
mc.inbox.dataArchivingJob=true
meicloud.paas.ies.upload.type=oss
meicloud.paas.ies.upload.endpoint=http://oss0c83-cn-baoding-gwmcloud-d01-a.ops.cloud.gwm.cn
meicloud.paas.ies.upload.accessKeyId=auv7eGlMODv7RCrK
meicloud.pass.ies.upload.accessKeySecret=ys4sgkPmhInCbtl7M1usxip9RNkhCq
meicloud.pass.ies.upload.bucketName=srm-dev
meicloud.paas.osca.type=${meicloud.paas.ies.upload.type}
meicloud.paas.osca.endPoint=${meicloud.paas.ies.upload.endpoint}
meicloud.paas.osca.accessKeyId=${meicloud.paas.ies.upload.accessKeyId}
meicloud.paas.osca.accessKeySecret=${meicloud.pass.ies.upload.accessKeySecret}
meicloud.paas.upload.minio.enable=false

apaas.loginType=local
apaas.login.local.username=admin
apaas.login.local.password=aPaaS@vip321
meicloud.paas.security.inbound.strategy=local

meiflow.sso.mode=THIRD_LOCAL
meiflow.sso.thirdAuthUrlPrefix=http://srm-java-gateway-dev.dev.svc.cluster.local:9005
meiflow.sso.thirdAppId=sQuq3nfarfwhNEdJ3c0w3kPdvvuSvHIa
meiflow.sso.getEncyptKeyUri=/cloud-srm/api-base/common/publicKey