-- 借阅管理

CREATE TABLE `scc_npm_borrow`
(
    `BORROW_ID`              bigint(20)  NOT NULL COMMENT '主键id',
    `BORROW_NUM`             varchar(30)  NOT NULL COMMENT '借阅申请单号',
    `STATUS`          varchar(50) NOT NULL COMMENT '状态',
    `BIDING_ID`              bigint(20)           DEFAULT NULL COMMENT '招标项目ID',
    `BIDING_NUM`             varchar(30)          DEFAULT NULL COMMENT '招标项目编码',
    `BIDING_NAME`            varchar(240)         DEFAULT NULL COMMENT '招标项目名称',
    `DEPARTMENT_ID`          bigint(20)           DEFAULT NULL COMMENT '部门id',
    `DEPARTMENT_CODE`        varchar(50)          DEFAULT NULL COMMENT '部门编码',
    `DEPARTMENT_NAME`        varchar(50)          DEFAULT NULL COMMENT '部门名称',
    `APPLY_USER_CODE`        varchar(50)          DEFAULT NULL COMMENT '申请人工号',
    `APPLY_USER_NAME`        varchar(50)          DEFAULT NULL COMMENT '申请人名称',
    `APPLY_CONTACTS`         varchar(50)          DEFAULT NULL COMMENT '申请人联系方式',
    `BORROW_TYPE`            varchar(50)          DEFAULT NULL COMMENT '借阅资料类型',
    `BORROW_CAUSE`           varchar(1000)          DEFAULT NULL COMMENT '申请使用原因',
    `USE_TYPE`               varchar(50)          DEFAULT NULL COMMENT '使用方式',
    `PRICE_FLAG`             varchar(10)          DEFAULT NULL COMMENT '是否涉及报价，Y/N',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`BORROW_ID`) USING BTREE,
    KEY `scc_npm_borrow_BIDING_NUM_IDX` (`BIDING_NUM`) USING BTREE
) ENGINE = InnoDB COMMENT ='借阅申请';

-- 借阅申请附件

CREATE TABLE `scc_npm_borrow_attach`
(
    `BORROW_ATTACH_ID`      bigint(20)  NOT NULL COMMENT '主键id',
    `BORROW_ID`             bigint(20)  NOT NULL COMMENT '考察申请id',
    `ATTACH_ID`              bigint(20)           DEFAULT NULL COMMENT '附件ID',
    `ATTACH_NAME`            varchar(50)          DEFAULT NULL COMMENT '附件名称',
    `ATTACH_PATH`              VARCHAR(200)           DEFAULT NULL COMMENT '附件路径',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`BORROW_ATTACH_ID`) USING BTREE,
    KEY `scc_npm_borrow_attach_BORROW_ID_IDX` (`BORROW_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='借阅附件';

-- 考察申请

CREATE TABLE `scc_npm_inspect`
(
    `INSPECT_ID`               bigint(20)  NOT NULL COMMENT '主键id',
    `INSPECT_NUM`              varchar(30)  NOT NULL COMMENT '考察申请单号',
    `REPORT_NUM`              varchar(30)  NOT NULL COMMENT '考察报告单号',
    `INSPECT_STATUS`           varchar(50) NOT NULL COMMENT '状态',
    `BIDING_ID`                bigint(20)           DEFAULT NULL COMMENT '招标项目ID',
    `BIDING_NUM`               varchar(30)          DEFAULT NULL COMMENT '招标项目编码',
    `BIDING_NAME`              varchar(240)         DEFAULT NULL COMMENT '招标项目名称',
    `BIDING_head`              varchar(240)         DEFAULT NULL COMMENT '招标项目负责人',
    `BIDING_DEPARTMENT_FLAG`   varchar(10)          DEFAULT NULL COMMENT '招标部是否参加，Y/N',
    `ORG_ID`                   bigint(20)           DEFAULT NULL COMMENT '业务实体ID',
    `ORG_CODE`                 varchar(50)          DEFAULT NULL COMMENT '业务实体编码',
    `ORG_NAME`                 varchar(50)          DEFAULT NULL COMMENT '业务实体名称',
    `DEPARTMENT_ID`            bigint(20)           DEFAULT NULL COMMENT '部门id',
    `DEPARTMENT_CODE`          varchar(50)          DEFAULT NULL COMMENT '部门编码',
    `DEPARTMENT_NAME`          varchar(50)          DEFAULT NULL COMMENT '部门名称',
    `COME_TYPE`                varchar(50)          DEFAULT NULL COMMENT '出行方式',
    `COMMENT`                  varchar(500)         DEFAULT NULL COMMENT '备注（拟参加人员）',
    `COMPREHENSIVE_EVALUATION` varchar(2000)         DEFAULT NULL COMMENT '综合评估意见',
    `LEADER_EVALUATION`        varchar(2000)         DEFAULT NULL COMMENT '组长评估意见',
    `CREATED_ID`               bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`               varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`            datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`            varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`        varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`          bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`          varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`         datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`       varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME`   varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`                varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                  bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`INSPECT_ID`) USING BTREE,
    KEY `scc_npm_inspect_BIDING_NUM_IDX` (`BIDING_NUM`) USING BTREE,
    KEY `scc_npm_inspect_INSPECT_NUM_IDX` (`INSPECT_NUM`) USING BTREE
) ENGINE = InnoDB COMMENT ='考察申请';


-- 考察申请附件

CREATE TABLE `scc_npm_inspect_attach`
(
    `INSPECT_ATTACH_ID`      bigint(20)  NOT NULL COMMENT '主键id',
    `INSPECT_ID`             bigint(20)  NOT NULL COMMENT '考察申请id',
    `ATTACH_ID`              bigint(20)           DEFAULT NULL COMMENT '附件ID',
    `ATTACH_NAME`            varchar(50)          DEFAULT NULL COMMENT '附件名称',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`INSPECT_ATTACH_ID`) USING BTREE,
    KEY `scc_npm_inspect_attach_INSPECT_ID_IDX` (`INSPECT_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='考察附件';


-- 考察申请单位

CREATE TABLE `scc_npm_inspect_vendor`
(
    `INSPECT_VENDOR_ID`      bigint(20)  NOT NULL COMMENT '主键id',
    `INSPECT_ID`             bigint(20)  NOT NULL COMMENT '考察申请id',
    `VENDOR_ID`              bigint(20)           DEFAULT NULL COMMENT '供应商ID',
    `VENDOR_NAME`            varchar(50)          DEFAULT NULL COMMENT '供应商名称',
    `VENDOR_CODE`            varchar(30)          DEFAULT NULL COMMENT '供应商编码',
    `INSPECT_ADDRESS`        varchar(50)          DEFAULT NULL COMMENT '地点',
    `INSPECT_CAUSE`          varchar(200)         DEFAULT NULL COMMENT '考察原因',
    `INSPECT_TIME`           datetime             DEFAULT NULL COMMENT '考察时间',
    `INSPECT_CONTENT`        varchar(500)         DEFAULT NULL COMMENT '考察内容',
    `MANAGE_EVALUATE`        varchar(500)         DEFAULT NULL COMMENT '现场管理评价',
    `DEVICE_EVALUATE`        varchar(500)         DEFAULT NULL COMMENT '生产设备评价',
    `STAFF_EVALUATE`         varchar(500)         DEFAULT NULL COMMENT '人员状况',
    `PERFORMANCE_EVALUATE`   varchar(500)         DEFAULT NULL COMMENT '绩效情况',
    `COMMENT`                varchar(500)         DEFAULT NULL COMMENT '其他方面',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`INSPECT_VENDOR_ID`) USING BTREE,
    KEY `scc_npm_inspect_vendor_INSPECT_ID_IDX` (`INSPECT_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='考察单位';


CREATE TABLE `scc_npm_inspect_user`
(
    `INSPECT_USER_ID`      bigint(20)  NOT NULL COMMENT '主键id',
    `INSPECT_ID`             bigint(20)  NOT NULL COMMENT '考察申请id',
    `USER_ID`              bigint(20)           DEFAULT NULL COMMENT '用户id',
    `USERNAME`            varchar(50)          DEFAULT NULL COMMENT '用户姓名',
    `COMPANY`            varchar(100)          DEFAULT NULL COMMENT '单位',
    `DEPARTMENT`        varchar(100)          DEFAULT NULL COMMENT '部门',
    `JOB_DESC`          varchar(100)         DEFAULT NULL COMMENT '岗位',
    `BID_FLAG`        varchar(10)         DEFAULT NULL COMMENT '是否评标组成员',
    `RESPONSIBILITY`        varchar(500)         DEFAULT NULL COMMENT '负责内容',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`INSPECT_USER_ID`) USING BTREE,
    KEY `scc_npm_inspect_vendor_INSPECT_ID_IDX` (`INSPECT_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='考察人员';

-- 招募

CREATE TABLE `scc_npm_recruit`
(
    `RECRUIT_ID`             bigint(20)  NOT NULL COMMENT '主键id',
    `NAME`                   varchar(50)          DEFAULT NULL COMMENT '名称',
    `TITLE`                  varchar(50)          DEFAULT NULL COMMENT '标题',
    `STATUS`                 varchar(50)          DEFAULT NULL COMMENT '状态',
    `CATEGORY_ID`            bigint(20)           DEFAULT NULL COMMENT '品类id',
    `CATEGORY_CODE`          VARCHAR(50)           DEFAULT NULL COMMENT '品类编码',
    `CATEGORY_NAME`          VARCHAR(50)           DEFAULT NULL COMMENT '品类名称',
    `PUBLISH_TIME`           datetime             DEFAULT NULL COMMENT '发布时间',
    `DEADLINE_TIME`          datetime             DEFAULT NULL COMMENT '截止时间',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`RECRUIT_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='招募';


-- 招募内容
CREATE TABLE `scc_npm_recruit_content`
(
    `RECRUIT_CONTENT_ID` bigint(20) NOT NULL COMMENT '主键id',
    `RECRUIT_ID`         bigint(20) NOT NULL COMMENT '招募id',
    `CONTENT`            text DEFAULT NULL COMMENT '内容',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`RECRUIT_CONTENT_ID`) USING BTREE,
    KEY `scc_npm_inspect_vendor_RECRUIT_ID_IDX` (`RECRUIT_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='招募内容';


-- 招募报名

CREATE TABLE `scc_npm_recruit_vendor`
(
    `RECRUIT_VENDOR_ID`      bigint(20)  NOT NULL COMMENT '主键id',
    `RECRUIT_ID`             bigint(20)  NOT NULL COMMENT '招募id',
    `COMPANY_NAME`           varchar(50)          DEFAULT NULL COMMENT '报名公司',
    `CONTACT_NAME`           varchar(50)          DEFAULT NULL COMMENT '报名联系人',
    `CONTACT_MOBILE`         varchar(50)          DEFAULT NULL COMMENT '报名联系电话',
    `CONTACT_EMAIL`          varchar(50)          DEFAULT NULL COMMENT '报名联系邮箱',
    `CREATED_ID`             bigint(20)  NOT NULL COMMENT '创建人ID',
    `CREATED_BY`             varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE`          datetime    NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP`          varchar(150)         DEFAULT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME`      varchar(100)         DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID`        bigint(20)           DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY`        varchar(50)          DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE`       datetime             DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP`     varchar(150)         DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100)         DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID`              varchar(30)          DEFAULT NULL COMMENT '租户ID',
    `VERSION`                bigint(20)  NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (`RECRUIT_VENDOR_ID`) USING BTREE,
    KEY `scc_npm_inspect_vendor_RECRUIT_ID_IDX` (`RECRUIT_ID`) USING BTREE
) ENGINE = InnoDB COMMENT ='招募供应商';


-- 招募状态字典
INSERT INTO `scc_base_dict` (`DICT_ID`, `DICT_CODE`, `DICT_NAME`, `DESCRIPTION`, `LANGUAGE`, `LANGUAGE_NAME`, `DICT_ROLE`, `DICT_ROLE_NAME`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295595020288, 'RECRUIT_STATUS', '招募状态', '', 'zh_CN', '中文', '', '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:25:55', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:25:55', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295739013120, 445295595020288, 'DRAFT', '拟定', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:06', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:06', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295788019712, 445295595020288, 'APPROVING', '审批中', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:30', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:30', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295817242624, 445295595020288, 'APPROVED', '已审批', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:44', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:44', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295844759552, 445295595020288, 'REJECTED', '已驳回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:57', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:57', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295868452864, 445295595020288, 'ABANDON', '已废弃', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:09', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:09', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297152, 445295595020288, 'WITHDRAW', '已撤回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);

-- 借阅状态字典
INSERT INTO `scc_base_dict` (`DICT_ID`, `DICT_CODE`, `DICT_NAME`, `DESCRIPTION`, `LANGUAGE`, `LANGUAGE_NAME`, `DICT_ROLE`, `DICT_ROLE_NAME`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295595020289, 'BORROW_STATUS', '借阅状态', '', 'zh_CN', '中文', '', '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:25:55', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:25:55', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297153, 445295595020289, 'DRAFT', '拟定', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:06', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:06', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297154, 445295595020289, 'APPROVING', '审批中', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:30', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:30', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297155, 445295595020289, 'APPROVED', '已审批', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:44', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:44', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297156, 445295595020289, 'REJECTED', '已驳回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:57', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:57', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297157, 445295595020289, 'ABANDON', '已废弃', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:09', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:09', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297158, 445295595020289, 'WITHDRAW', '已撤回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);

-- 考察报告
INSERT INTO `scc_base_dict` (`DICT_ID`, `DICT_CODE`, `DICT_NAME`, `DESCRIPTION`, `LANGUAGE`, `LANGUAGE_NAME`, `DICT_ROLE`, `DICT_ROLE_NAME`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295595020290, 'INSPECT_STATUS', '考察状态', '', 'zh_CN', '中文', '', '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:25:55', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:25:55', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297159, 445295595020290, 'DRAFT', '拟定', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:06', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:06', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297160, 445295595020290, 'APPLY_APPROVING', '申请审批中', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:30', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:30', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297161, 445295595020290, 'APPLY_WITHDRAW', '申请已撤回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:44', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:44', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297162, 445295595020290, 'APPLY_REJECTED', '申请已驳回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:27:57', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:27:57', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297163, 445295595020290, 'APPLY_APPROVED', '待提交报告', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:09', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:09', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297164, 445295595020290, 'REPORT_APPROVING', '报告审批中', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297165, 445295595020290, 'REPORT_WITHDRAW', '报告已撤回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297166, 445295595020290, 'REPORT_REJECTED', '报告已驳回', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297167, 445295595020290, 'REPORT_APPROVED', '报告已审批', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);
INSERT INTO `scc_base_dict_item` (`DICT_ITEM_ID`, `DICT_ID`, `DICT_ITEM_CODE`, `DICT_ITEM_NAME`, `ITEM_LANGUAGE`, `ITEM_LANGUAGE_NAME`, `ITEM_DESCRIPTION`, `DICT_ITEM_NO`, `DICT_ITEM_MARK`, `ACTIVE_DATE`, `INACTIVE_DATE`, `CREATED_ID`, `CREATED_BY`, `CREATION_DATE`, `CREATED_BY_IP`, `CREATED_FULL_NAME`, `LAST_UPDATED_ID`, `LAST_UPDATED_BY`, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY_IP`, `LAST_UPDATED_FULL_NAME`, `TENANT_ID`, `VERSION`) VALUES (445295893297168, 445295595020290, 'ABANDON', '已废弃', 'zh_CN', '中文', '', NULL, '', '2023-10-18', NULL, 8123195817787648, 'super', '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, NULL, '2023-10-18 10:28:21', '10.254.103.156', '超级管理员', NULL, 0);



-- 快查
-- scc_npm_sou_project 招标快查
-- scc_npm_respect_vendor 考察管理-供应商查询
