srm.jd.clientId=QnNqFCoFJn5f1gy795eI
srm.jd.clientSecret=Toqzs8HLRSUpDeoD2qKB
srm.jd.username=长城汽车平台采购账号
srm.jd.password=123456aa
srm.jd.accessTokenUrl=https://api-iop.jd.com/oauth2/accessToken
srm.jd.refreshTokenUrl=https://api-iop.jd.com/oauth2/refreshToken
srm.jd.getJDAddressFromAddressUrl=https://api-iop.jd.com/api/area/getJDAddressFromAddress
srm.jd.getPageNumUrl=https://api-iop.jd.com/api/product/getPageNum
srm.jd.querySkuUrl=https://api-iop.jd.com/api/product/querySkuByPage
srm.jd.productDetailUrl =https://api-iop.jd.com/api/product/getDetail
srm.jd.skuImageUrl =https://api-iop.jd.com/api/product/skuImage
srm.jd.skuStateUrl =https://api-iop.jd.com/api/product/skuState
srm.jd.getNewStock =https://api-iop.jd.com/ api/stock/getNewStockById
srm.jd.submitOrder =https://api-iop.jd.com/api/order/submitOrder
srm.jd.selectJdOrderUrl =https://api-iop.jd.com/api/order/selectJdOrder
srm.jd.orderTrackUrl =https://api-iop.jd.com/api/order/orderTrack
srm.jd.confirmReceivedUrl=https://api-iop.jd.com/api/order/confirmReceived
srm.jd.batchConfirmReceivedUrl =https://api-iop.jd.com/api/order/batchConfirmReceived
srm.jd.getPromiseTipsUrl =https://api-iop.jd.com/api/order/getPromiseTips
srm.jd.getGoodsAttributesUrl =https://api-iop.jd.com/api/afterSaleNew/getGoodsAttributes
srm.jd.createAfsApplyUrl =https://api-iop.jd.com/api/afterSaleNew/createAfsApply
srm.jd.getAfsOutlineUrl =https://api-iop.jd.com/api/afterSaleNew/getAfsOutline
srm.jd.updateSendInfoUrl =https://api-iop.jd.com/api/afterSaleNew/updateSendInfo
srm.jd.cancelAfsApplyUrl =https://api-iop.jd.com/api/afterSaleNew/cancelAfsApply
srm.jd.queryRenewOrderRelationshipInfosUrl =https://api-iop.jd.com/api/afterSaleNew/queryRenewOrderRelationshipInfos
srm.jd.getApplyDetailInfoUrl =https://api-iop.jd.com/api/afterSaleNew/getApplyDetailInfo
srm.jd.invoiceSubmitUrl =https://api-iop.jd.com/api/invoice/submit
srm.jd.invoiceSelectUrl =https://api-iop.jd.com/api/invoice/select
srm.jd.queryInvoiceItemUrl =https://api-iop.jd.com/api/invoice/queryInvoiceItem
srm.jd.waybillUrl =https://api-iop.jd.com/api/invoice/waybill
srm.jd.queryDeliveryNoUrl =https://api-iop.jd.com/api/invoice/queryDeliveryNo
srm.jd.imgBaseUrl =https://img13.360buyimg.com/n1/
srm.jd.totalCheckNewUrl=https://api-iop.jd.com/api/product/totalCheckNew
srm.jd.getMessageUrl=https://api-iop.jd.com/api/message/get
srm.jd.delMessageUrl=https://api-iop.jd.com/api/message/del
srm.jd.saveOrUpdatePoNoUrl=https://api-iop.jd.com/api/order/saveOrUpdatePoNo
srm.jd.getSellPriceUrl=https://api-iop.jd.com/api/price/getSellPrice
