apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-java-config
  namespace: {{ .Values.global.namespace }}
data:
  bootstrap-extenddev.yml: |-
    # dev环境配置
    spring:
      cloud:
        config:
          profile: dev
        #      name: application-extenddockeruat,${spring.application.name}
        nacos:
          discovery:
            # 命名空间，注册到srm-dockeruat环境
            namespace: {{ .Values.global.nacos.discovery.namespace }}
            # 注册中心地址
            server-addr: {{ .Values.global.nacos.discovery.serverAddr }}
            group: {{ .Values.global.nacos.discovery.group }}
            metadata:
              # feign微服务调用路由策略标签分组
              routingTag: dev
          config:
            # 命名空间，获取srm-dockeruat命名空间的配置文件
            namespace: {{ .Values.global.nacos.config.namespace }}
            group: {{ .Values.global.nacos.config.group }}
            # 配置中心地址
            server-addr: {{ .Values.global.nacos.config.serverAddr }}
      devtools:
        restart:
          enabled: true

    # 微服务feign调用自定义路由策略，优先按照标签组[微服务元数据metadata.routingTag值]调用
    ribbon:
      rule: tag

    # swagger文档
    knife4j:
      production: false

  bootstrap.yml: |-
    jasypt.encryptor.password: {{ .Values.global.jasypt.password }}
    # dev环境配置
    spring:
      profiles:
        active: {{ .Values.global.profiles }}
      cloud:
        # 配置中心切换到nacos，下面注释掉的配置忽略
        #    config:
        #      discovery:
        #        enabled: true
        #        serviceId: config-center
        nacos:
          # nacos 注册中心通用配置
          discovery:
            metadata:
              appName: ${spring.application.name}
              internalAnonPassword: ${spring.cloud.client.hostname}-${spring.cloud.client.ipaddress}-${server.port}-${sysRandom:CsaWljuYd1}
              externalAnonPassword: ${spring.cloud.client.hostname}-${spring.cloud.client.ipaddress}-${server.port}-${sysRandom:uqlWlqcW*9}
            service: ${spring.application.name}
          # nacos 配置中心通用配置
          config:
            refresh-enabled: true
            file-extension: yml
            shared-configs:
              - data-id: global-env.properties
                refresh: true
                group: {{ .Values.global.nacos.discovery.global_group }}
              - data-id: srm-env.properties
                refresh: true
                group: {{ .Values.global.nacos.config.group }}
              - data-id: srm-init.properties
                refresh: true
                group: {{ .Values.global.nacos.config.group }}
            extension-configs:
              - data-id: srm-common.yml
                refresh: true
                group: {{ .Values.global.nacos.config.group }}
              # 只有base会用，为免配置修改时出错，暂时先放一起
              - data-id: srm-openresty.yml
                refresh: true
                group: {{ .Values.global.nacos.config.group }}
      mvc:
        pathmatch:
          matching-strategy: ANT_PATH_MATCHER
    server:
      max-http-header-size: 102400

    # eureka 切换到 nacos 注册中心，下面eureka注释掉的通用配置忽略
    #eureka:
    #  client:
    #    registry-fetch-interval-seconds: 5
    #  instance:
    #    lease-expiration-duration-in-seconds: 15
    #    lease-renewal-interval-in-seconds: 5
    #    prefer-ip-address: true
    #    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.ip-address}:${server.port}
    jasypt:
      encryptor:
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
        bean: sm4Encryptor #指定使用sm4算法

