#redis
ipaas.redis.database=11

#mysql
ipaas.db.host=${global.db.host}
ipaas.db.port=${global.db.port}
ipaas.db.username=${global.db.username}
ipaas.db.password=${global.db.password}
ipaas.db.schema=${global.mysqldb.prefix}ins_ipaas_prd
ipaas.db.store.schema=${global.mysqldb.prefix}ins_ipaas_store

#rocketmq
ipaas.rocketmq.name-server=${global.rocketmq.name-server}
ipaas.rocketmq.accessKey=${global.rocketmq.accessKey}
ipaas.rocketmq.secretKey=${global.rocketmq.secretKey}

#xxl-job
ipaas.xxljob.addresses=${global.xxljob.addresses}
ipaas.xxljob.accessToken=${global.xxljob.accessToken}
ipaas.xxljob.password=${global.xxljob.password}
ipaas.xxljob.executor.appname=ipaas-task-${global.env}-group
ipaas.xxljob.logpath=/apps/logs/xxl-job/jobhandler

#es
ipaas.es.url=${global.es.url}
ipaas.es.accessKey=${global.es.accessKey}
ipaas.es.secretKey=${global.es.secretKey}

#iam
ipaas.iam.domain=${global.iam.register-address}
ipaas.iam.accessKeyId=bkT4rm2PWiQ7
ipaas.iam.accessKeySecret=WRfdyCcgabQdnPBYlxL5tcwmUkO5bVGqiiMKV7DM2yK9QYtn
ipaas.iam.namespace=${global.nacos.namespace}
ipaas.iam.group=${global.nacos.group}
ipaas.iam.upmContext=${iam.upm.application.context}
ipaas.iam.authContext=${iam.auth.application.context}