import { createAPI } from './api-utils'

const API_COMMON_CACHE_CONFIG = {
  LIST_DICT: ['POST', 'COMMON_CACHE_LIST_DICT'],
  LIST_DICT_BATCH: ['POST', 'COMMON_CACHE_LIST_DICT_BATCH'],
  LIST_UNIT: ['POST', 'COMMON_CACHE_LIST_UNIT'],
  LIST_CURRENCY: ['POST', 'COMMON_CACHE_LIST_CURRENCY'],
  LIST_TAX: ['POST', 'COMMON_CACHE_LIST_TAX']
}

const API_COMMON_CACHE = createAPI(API_COMMON_CACHE_CONFIG, 'STORE_COMMON_CACHE')

export {
  API_COMMON_CACHE
}
export default {
  API_COMMON_CACHE
}
