#环境标识位
global.env=dev
#mysql
#数据库schema前缀标志位
global.mysqldb.prefix=meicloud_
global.mysqldb.suffix=
#JDBC数据库连接参数
global.jdbc.connection.params=useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true

#redis
#redission的单机/集群配置
global.redis.address=10.168.130.50:6379
global.redis.password=root
##standalone/cluster
global.redis.type=standalone
global.redis.host=10.168.130.50
global.redis.port=6379
#singleton/cluster
global.redis.schema=singleton

#spring.redis
#springboot2 redis单机配置
spring.redis.host=10.168.130.50
spring.redis.port=6379
spring.redis.password=${global.redis.password}
spring.redis.schema=singleton

#redis公共配置 springboot3.x
spring.data.redis.password=${global.redis.password}
spring.data.redis.host=${global.redis.host}
spring.data.redis.port=${global.redis.port}

#mail
global.mail.server_host=mail.hmmr.ru
global.mail.server_port=587
global.mail.user_name=srmplatformtest
global.mail.user_password=root
global.mail.from_address=srmplatformtest@hmmr.ru

#rocketmq
global.rocketmq.name-server=10.168.130.50:9876
global.rocketmq.accessKey=RocketMQ
global.rocketmq.secretKey=root

#zk
global.zk.host=""
global.zk.port=""

#xxl-job
global.xxljob.addresses=http://xxl-job-admin.dev:8080/xxl-job-admin
#默认default_token
global.xxljob.accessToken=s~P_~52z~hb4
global.xxljob.username=admin
global.xxljob.password=root

#minio配置
global.minio.url=http://10.168.130.50:9000
global.minio.accessKey=admin
global.minio.secretKey=root

#nacos配置
#global.nacos.url=http://nacos-cs.dev:8848
global.nacos.url=http://10.168.154.42:8848
global.nacos.namespace=dev
global.nacos.group=dev
global.nacos.user=nacos
global.nacos.password=nacos

#es
global.es.url=10.168.130.50:9200
#es的ip列表,逗号分割
global.es.hosts=10.168.130.50
#es的端口,只有一个
global.es.port=9200
global.es.schema=http
global.es.accessKey=elastic
global.es.secretKey=root

#seata
#默认default
global.seata.group="default"
#默认spring.cloud.nacos.config.namespace
global.seata.config.nacos.namespace="seata"
#默认SEATA_GROUP
global.seata.config.nacos.group="SEATA_GROUP"
#默认seataServer.properties
global.seata.config.nacos.dataId="seataServer.properties"
#默认seata-server
global.seata.registry.nacos.application="seata-server"
#默认seata.config.nacos.namespace
global.seata.registry.nacos.namespace="seata"
#默认seata.config.nacos.group
global.seata.registry.nacos.group="SEATA_GROUP"

#审计日志
global.audit.register-address=https://srm-apaas.hmmr.ru
#默认global.rocketmq.name-server
global.audit.rocketmq.name-server=${global.rocketmq.name-server}
global.audit.rocketmq.topic=audit-log-topic-dev
#默认audit-log-group
global.audit.rocketmq.groupName=audit-log-group-dev
#审计日志采用es存储时，索引名称（如果采用mysql存储，则本配置项无效）
global.audit.es.index-name=apaas_audit_event_log

#没有安装iam时
global.iam.register-address=127.0.0.1
global.iam.domain=127.0.0.1
#默认global.rocketmq.name-server
global.iam.rocketmq.name-server=${global.rocketmq.name-server}
global.iam.rocketmq.topic=IAMdev
iam.upm.application.context=iam/upm
iam.auth.application.context=iam/auth

#访问地址，IAM登录后的回调地址
global.srm.register-address=https://srm-dev.hmmr.ru
global.iet.register-address=https://srm-apaas.hmmr.ru
global.apaas.register-address=https://srm-apaas.hmmr.ru
global.audit.callback-address=${global.apaas.register-address}/audit
global.mc.register-address=${global.apaas.register-address}/mc
global.bpm.register-address=${global.apaas.register-address}/mflow

global.ipaas.register-address=https://srm-ipaas.hmmr.ru/flow

#迁移工具 通用变量
meicloud.migration.placeholders.nacos-address=http://10.168.154.42:8848
meicloud.migration.placeholders.nacos-ns=dev
meicloud.migration.placeholders.nacos-group=dev
meicloud.migration.placeholders.nacos-username=nacos
meicloud.migration.placeholders.nacos-password=nacos

#迁移工具 流程
meicloud.migration.migration-api.mflow.contentType=json
meicloud.migration.migration-api.mflow.api=${global.bpm.register-address}/be/design/model/migration/in?async=1
meicloud.migration.migration-api.mflow.statusApi=${global.bpm.register-address}/be/design/model/migration/task/{taskId}

#迁移工具 ipaas
meicloud.migration.migration-api.ipaas.contentType=file
meicloud.migration.migration-api.ipaas.api=${global.ipaas.register-address}/api/ipaas-admin/flow_migrate/f7fWsDtoT39uDer8/import
meicloud.migration.migration-api.ipaas.statusApi=${global.ipaas.register-address}/api/ipaas-admin/flow_migrate/f7fWsDtoT39uDer8/{taskId}

#域名使用的协议是http还是https
global.httpProtocol=https

bpmp.service-name=bpmp-service
bpmp.context-path=/bpmp
material.service-name=${bpmp.service-name}
material.context-path=${bpmp.context-path}
base.service-name=${bpmp.service-name}
base.context-path=${bpmp.context-path}
inventory.service-name=${bpmp.service-name}
inventory.context-path=${bpmp.context-path}
order.service-name=${bpmp.service-name}
order.context-path=${bpmp.context-path}
price.service-name=${bpmp.service-name}
price.context-path=${bpmp.context-path}
trader.service-name=${bpmp.service-name}
trader.context-path=${bpmp.context-path}
delivery.service-name=${bpmp.service-name}
delivery.context-path=${bpmp.context-path}

#logback日志的设定
#日志保留的天数
log.maxHistory=30
#日志文件滚动分割大小值，例如设置100MB，当日志超过100MB时，另起一个新日志文件继续写
log.maxFileSize=100MB
global.db.host=10.168.130.234
#global.db.host=127.0.0.1
global.db.port=3306
global.db.username=root
global.db.password=Guo@haval#2024

# Попытки отключить шифрование ошибок
meicloud.common.error.encrypt=false
srm.common.error.encrypt=false
spring.mvc.throw-exception-if-no-handler-found=true
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.midea.cloud.srm.feign=DEBUG
feign.client.config.default.loggerLevel=FULL

# gwm integration
#gwm.prdAppkey=key-for-local-dev
#gwm.prdSecret=key-for-local-dev
#gwm.preappkey=key-for-local-dev
#gwm.presecret=key-for-local-dev
#gwm.url.branchBankSyncFromOpen-url=dev-url
#gwm.bpm.src-system=dev
spring.cloud.config.profile=dev
iam.iamDomain=http://localhost
ipaas.flow.api=http://127.0.0.1:8080/flow/api
ipaas.flow.gscp_token_url=""
ipaas.flow.gscp_import_screening_url=""


# GWM Integration Config
gwm.appkey=85X2XXT7MAXX
gwm.appId=com.awspaas.user.apps.srm20240129
gwm.secret=021f2270513c462aab6453e37d15dfd8
gwm.opersource=RUS_SRM
gwm.preappkey=850T8A7B9648
gwm.presecret=acfae103027447838b0c019ca278b0e6
gwm.srmbpmTodoGroupId=obj_17a51da90e80426b96370ff570114d70

# OCR URLs
gwm.recognizeLicenceOcrUrl=https://gwapi.gwm.cn/rest/public/pubqc/api/tripartite/ocr/ticket/BizLicenseOCR
gwm.recognizeIDCardFrontOcrUrl=https://gwapi.gwm.cn/rest/public/pubqc/api/tripartite/ocr/ticket/idCard
gwm.recognizeIDCardBackOcrUrl=https://gwapi.gwm.cn/rest/public/pubqc/api/tripartite/ocr/ticket/idcardne

# Production OCR (fallback)
gwm.prdAppkey=6SS4T6X52X40
gwm.prdSecret=4c35a4eed7824afdb3f988b51ec42a54

# Internal Supplier
gwm.internalSupplier.appKey=6SS4T6X52X40
gwm.internalSupplier.secret=4c35a4eed7824afdb3f988b51ec42a54
gwm.internalSupplier.appCode=13192890f4c64de38ff5e6ce593b8def

# SSO
gwm.sso.getUserInfoByTokenUrl=http://auth.test.paas.gwm.cn/authenticate/getUserInfoByToken
gwm.sso.verifyTokenUrl=https://srm-cnp-bdtest.gwm.cn/cloud-srm/sys/verifyToken
gwm.sso.platform_code=692e8def19081157c0c6cbfbce95ed95

# Knowledge Brain (GWKB)
gwm.gwkb.appkey=58f916def80d4fa2bea51027b9def100
gwm.gwkb.secret=6d4ad22e46424b27a5ddc78b37a1efab
gwm.gwkb.login-url=https://gwkb-test.gwm.cn/prod-api/auth/login
gwm.gwkb.fileCompare-url=https://gwkb-test.gwm.cn/prod-api/mindmatrix/fileCompare/getSRMResult
gwm.gwkb.bidReviewPush-url=https://gwkb-test.gwm.cn/prod-api/mindmatrix/bidReview/push
gwm.gwkb.bidReviewScanFile-url=https://gwkb-test.gwm.cn/prod-api/mindmatrix/bidReview/getParseFailedFileList
gwm.gwkb.bidReviewItemsQuotation-url=https://gwkb-test.gwm.cn/prod-api/mindmatrix/bidReview/getItemsQuotation

# BPM
gwm.bpm.src-system=com.awspaas.user.apps.app20230971602
gwm.bpm.api-username=GW00244106

# URLs
gwm.url.branchBankSyncFromOpen-url=https://gwapi.gwm.cn/rest/fd/fund/fd/fund/zj/serach/api/dtxg/cc/BASE-0117
gwm.url.sunHonestySysPushUser-url=http://10.251.84.14/api/open/receiveUserServer
gwm.url.sunHonestySys-getPreAuthCode-url=http://10.251.84.14/api/getPreAuthCode
gwm.url.sunHonestySys-platformCode=9913cc1c46a546ff9cc54746d0d82a43
gwm.url.sunHonestySys-encryptKey=483bf82e315b4600
gwm.url.sunHonestySys-externalSso-url=http://10.251.84.14:8089/externalSso?code=%s&platformCode=%s&redirectUrl=trainingTasks?id=643
gwm.url.getSupplierWinningRateByVendoridOrCode-url=http://bc474ee84e4245cc86b911b7549894f6.apigateway.res.cloud.gwm.cn/sc/srm/getSupplierWinningRateByVendorId?appCode=414ddb6d1aeb4db2963de3dddf193935&vendor_id=%s
gwm.url.getSupHistoricalCooperationByIdOrCode-url=http://bc474ee84e4245cc86b911b7549894f6.apigateway.res.cloud.gwm.cn/sc/srm/getSupHistoricalCooperationByVendorId?appCode=414ddb6d1aeb4db2963de3dddf193935&vendor_id=%s
gwm.url.org-list=https://gwapi.gwm.cn/sandbox/hr/staff/domain/org/list
gwm.url.employee-list=https://gwapi.gwm.cn/sandbox/hr/staff/domain/employee/list
gwm.url.user-info=https://gwapi.gwm.cn/rest/hr/staff/domain/employee/get
gwm.url.user-info-batch=https://gwapi.gwm.cn/rest/hr/staff/domain/employee/get/batch
gwm.url.flow-create=https://gwapi.gwm.cn/pre/public/flow/native/createProcess
gwm.url.flow-update=https://gwapi.gwm.cn/pre/public/flow/native/updateBoData
gwm.url.flow-resubmit=https://gwapi.gwm.cn/pre/public/flow/native/resubmitProcess
gwm.url.startProcessByCategoty-url=https://gwapi.gwm.cn/pre/public/flow/thirdSys/startProcessByCategoty
gwm.url.rollBackTask-url=https://gwapi.gwm.cn/pre/public/flow/thirdSys/rollBackTask
gwm.url.forwardTask-url=https://gwapi.gwm.cn/pre/public/flow/thirdSys/forwardTask
gwm.url.commitTask-url=https://gwapi.gwm.cn/pre/public/flow/thirdSys/commitTask
gwm.url.predict-url=https://bpmuat.gwm.cn/bpmapi/process/predict
gwm.url.process-comment-info=https://gwapi.gwm.cn/pre/public/flow/common/comment/getCommentAndTodoTaskList
gwm.url.blackcompany-info=https://gwapi.gwm.cn/sandbox/public/mdm/sun/blackcompany/info
gwm.url.create-supplier=https://gwapi.gwm.cn/sandbox/mdm/supplierinfo/supplierinfo/createSupplier
gwm.url.create-supplierview=https://gwapi.gwm.cn/sandbox/pd/product/api/erp/material/gateway/gwm-controller/sapWebService/createSuppliCompanyView
gwm.url.find-supplierByName=https://gwapi.gwm.cn/sandbox/mdm/supplierinfo/supplierinfo/searchListByFullName
gwm.url.find-supplierByTaxcodes=https://gwapi.gwm.cn/sandbox/mdm/supplierinfo/supplierinfo/searchListByTaxCodes
gwm.url.receive-blackcompany=https://gwapi.gwm.cn/sandbox/public/mdm/sun/blackcompany/searchPage
gwm.url.edit-supplier=https://gwapi.gwm.cn/sandbox/mdm/supplierinfo/supplierinfo/edit
gwm.url.company-aqc=http://10.255.128.79:81/gwm_ips/rest/SrmPassUtil/searchCompany
gwm.url.category=https://gwapi.gwm.cn/sandbox/mdm/Nonproductionmaterials/material-category/page
gwm.url.findToken-url=http://gscp.gwmtest.cn/AuthServer/oauth/token
gwm.url.findTokenUsername=DPS
gwm.url.findTokenPassword=DPSshaicha.1
gwm.url.import-screening=http://gscp.gwmtest.cn/api/asm-screening-api/v1/import-screening
gwm.url.import-screening-accountId=1003
gwm.url.import-screening-datasetId=1067
gwm.url.import-screening-profileId=4a636fe2-d1d1-4e2c-a65d-8f2da5f13e43
gwm.url.dingding-workNotices-url=https://gwapi.gwm.cn/sandbox/msg/dingding/workNotices
gwm.url.feishu-workNotices-url=https://gwapi.gwm.cn/sandbox/public/news/msg/fs-msg-info/send-batch-msg
gwm.url.sms-notice-url=https://gwapi.gwm.cn/rest/public/pubqc/api/tripartite/capability/notification3
gwm.url.sms-Submit-url=http://www.dh3t.com/json/sms/Submit3
gwm.url.sms-Submit-account=111
gwm.url.sms-Submit-password=To82Tiq9
gwm.url.sms-Submit-sign=【长城汽车】
gwm.url.sendEmail-url=https://gwapi.gwm.cn/sandbox/rd/email/send/text
gwm.url.searchListByTaxCodes-url=https://gwapi.gwm.cn/sandbox/mdm/supplierinfo/supplierinfo/searchListByTaxCodes
gwm.url.flowCategory-create=https://gwapi.gwm.cn/pre/public/flow/native/createProcessByCategory
gwm.url.flow-rollBack=https://gwapi.gwm.cn/pre/public/flow/native/rollBackProcess
gwm.url.contractLock-createbyfiles=http://10.255.128.120:8182/
gwm.url.accessKey=oRgwc3NkL6
gwm.url.accessSecret=YWLkTOmqP2PAL0qfXUJwAnWOoXoLgC
gwm.url.categoryId=3150019311663075996
gwm.url.organizationRole=https://gwapi.gwm.cn/pre/public/flow/dw/bo/updateDwBoData
gwm.url.price-rate-url=https://gwapi.gwm.cn/rest/mdm/exchangerate/rate/page
gwm.url.internalSupplier-url=https://gwapi.gwm.cn/rest/fd/fdqc/fi/md/com/fi/com/getLegalCompanyByCreditCode
gwm.url.logisticsInfo-url=https://gwapi.gwm.cn/rest/sc/kuaidi100/orderQuery/kuaidi100/orderQuery
gwm.url.createContract-url=https://gwapi.gwm.cn/sandbox/LF/agreement/lcss/contract/legal/contract/sync/collect/v1
gwm.url.material-url=https://gwapi.gwm.cn/sandbox/mdm/Nonproductionmaterials/nonproductive-material/page
gwm.url.incorporated-company-info-url=https://gwapi.gwm.cn/sandbox/mdm/incorporatedCompany/incorporated-company-info/page
gwm.url.invoiceSearchUrl=https://gwapi.gwm.cn/sandbox/fd/inv1/income/invoice/invoice/capability/invoice/invoiceListQuery
gwm.url.invoiceReimburseUrl=https://gwapi.gwm.cn/sandbox/fd/inv1/income/invoice/invoice/capability/invoice/reimburseUpdate
gwm.url.user-mployeeCompanyPage=https://gwapi.gwm.cn/sandbox/hr/staff/roster/open/employee/company/pageCustomEmployee
gwm.url.org-companyPageByParentId=https://gwapi.gwm.cn/sandbox/hr/staff/roster/open/organization/company/getOrgTreeByParentId
gwm.url.claimUrl=https://gwapi.gwm.cn/pre/fd/fund/fd/fund/zj/serach/api/dtxg/cc/ARMG-1002
gwm.url.receivableUrl=https://gwapi.gwm.cn/pre/fd/fund/fd/fund/zj/serach/api/dtxg/cc/ARMG-1003
gwm.url.receiveUrl=https://gwapi.gwm.cn/pre/fd/fund/fd/fund/zj/serach/api/dtxg/cc/ARMG-1001
gwm.url.createEAITaskInstanceUrl=https://gwapi.gwm.cn/sandbox/public/bpm/portal/api/customAPI/task/createEAITaskInstance
gwm.url.completeEAITaskUrl=https://gwapi.gwm.cn/sandbox/public/bpm/bpmeai/task/completeEAITask
gwm.url.createInvoiceUrl=https://gwapi.gwm.cn/sandbox/fd/sif/sale/settle/api/cwgxsettle/sale/settle/create/invoice
gwm.url.settleResultUrl=https://gwapi.gwm.cn/sandbox/fd/sif/sale/settle/api/cwgxsettle/sale/settle/result
gwm.url.edmPurOrderPushUrl=http://edm.hmmr.ru/scim-edm-service/scim-edm-sparepart/SRM/receiveOrder
gwm.url.edmPurDraftPushUrl=http://edm.hmmr.ru/scim-edm-service/scim-edm-sparepart/SRM/updatePurchApplyState
gwm.url.paymentSaveOutSourceOneUrl=https://gwapi.gwm.cn/sandbox/fd/fdqc/paymentRequest/saveOutSourceOneVo/paymentRequest/saveOutSourceOneVo
gwm.url.settleAccounting=https://gwapi.gwm.cn/sandbox/fd/sif/sale/settle/api/cwgxsettle/sale/settle/accounting