<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sdk-project-impl</artifactId>
        <groupId>com.midea</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sdk-project-contract-impl</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>sdk-contract-interface</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>meiql-starter-extend</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>sdk-project-entity</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-api-pj</artifactId>
            <version>1.0-russia-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.googlecode.aviator</groupId>
                    <artifactId>aviator</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-commons-pj</artifactId>
            <version>1.0-russia-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.googlecode.aviator</groupId>
                    <artifactId>aviator</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>e-iceblue</groupId>
            <artifactId>spire.pdf.free</artifactId>
            <version>5.1.0</version>
        </dependency>
        <dependency>
            <groupId>e-iceblue</groupId>
            <artifactId>spire.doc.free</artifactId>
            <version>5.1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/spire.doc.free-5.1.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>meiql-open-client-extend</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.5.10</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itext-asian</artifactId>
            <version>5.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf.tool</groupId>
            <artifactId>xmlworker</artifactId>
            <version>5.5.11</version>
        </dependency>
        <dependency>
            <groupId>com.midea</groupId>
            <artifactId>cloud-biz-contract-extend</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
        <resource>
            <directory>src/main/resources</directory>
            <includes>
                <include>**/*</include>
            </includes>
        </resource>
        <resource>
            <directory>lib</directory>
            <includes>
                <include>**/*</include>
            </includes>
            <targetPath>../</targetPath>
        </resource>
        <resource>
            <directory>../sdk-project-entity/target/classes/</directory>
            <includes>
                <include>**/*</include>
            </includes>
            <targetPath>../sdk-project-entity</targetPath>
        </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.2</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeArtifactIds>
                                sdk-project-entity,cloud-biz-api-pj,cloud-biz-commons-pj,spire.pdf.free,meiql-open-client-extend,sies-starter-extend,
                                feign-slf4j,
                                auth,
                                s3,
                                jna,
                                osca-common,
                                ies-common,
                                huaweicloud-sdk-core,
                                profiles,
                                eventstream,
                                jopt-simple,
                                utils,
                                ies-sdk,
                                third-party-jackson-core,
                                parent-join-client,
                                sdk-core,
                                esdk-obs-java,
                                elasticsearch,
                                joda-time,
                                stax-api,
                                cpdetector,
                                aliyun-java-sdk-core,
                                ies-core,
                                aws-query-protocol,
                                jdom2,
                                aws-xml-protocol,
                                compiler,
                                logging-interceptor,
                                jettison,
                                aws-core,
                                hppc,
                                tencentcloud-sdk-java-kms,
                                huaweicloud-sdk-iam,
                                aggs-matrix-stats-client,
                                aliyun-java-sdk-ram,
                                netty-nio-client,
                                protocol-core,
                                tencentcloud-sdk-java-common,
                                simple-xml-safe,
                                mapper-extras-client,
                                rank-eval-client,
                                aliyun-sdk-oss,
                                osca-core,
                                regions,
                                paas-boot-core-starter,
                                aliyun-java-sdk-ecs,
                                minio,
                                cos-sts_api,
                                t-digest,
                                jackson-dataformat-smile,
                                jackson-dataformat-cbor,
                                elasticsearch-x-content,
                                arns,
                                metrics-spi,
                                aliyun-java-sdk-sts,
                                http-client-spi,
                                aliyun-java-sdk-kms,
                                json-utils,
                                lang-mustache-client,
                                cos_api,
                                xmlworker,
                                itext-asian,
                            </includeArtifactIds>
                            <includeGroupIds>
                                com.midea,e-iceblue,io.github.openfeign,software.amazon.awssdk,org.elasticsearch,org.apache.lucene,org.elasticsearch.client,com.meicloud.paas,com.huaweicloud.sdk,software.amazon.eventstream,net.sf.jopt-simple,com.midea,org.elasticsearch.plugin,com.huaweicloud,joda-time,stax,com.github.jiangxincode,com.aliyun,org.jdom,com.github.spullara.mustache.java,com.squareup.okhttp,org.codehaus.jettison,com.carrotsearch,com.tencentcloudapi,com.carrotsearch.thirdparty,com.aliyun.oss,io.minio,com.qcloud,com.tdunning,com.fasterxml.jackson.dataformat,
                                com.itextpdf.tool,com.itextpdf
                            </includeGroupIds>
                            <excludeGroupIds>
                                com.mideacloud
                            </excludeGroupIds>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <excludeTransitive>false</excludeTransitive>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-dependency-plugin</artifactId>-->
<!--                <version>3.1.2</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        &lt;!&ndash; unpack任务标识符，unpack是将依赖从仓库中解压到指定目录 &ndash;&gt;-->
<!--                        <id>unpack</id>-->
<!--                        &lt;!&ndash; unpack任务默认执行阶段 &ndash;&gt;-->
<!--                        <phase>generate-sources</phase>-->
<!--                        <goals>-->
<!--                            &lt;!&ndash; 目标功能：unpack &ndash;&gt;-->
<!--                            <goal>unpack</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <artifactItems>-->
<!--                                <artifactItem>-->
<!--                                    <groupId>com.midea</groupId>-->
<!--                                    <artifactId>sdk-project-entity</artifactId>-->
<!--                                    <version>${project.version}</version>-->
<!--                                    &lt;!&ndash; 设置为false，依赖解压到目录时不会进行覆盖，设置为true则会覆盖 &ndash;&gt;-->
<!--                                    <overWrite>false</overWrite>-->
<!--                                    &lt;!&ndash; 目标class文件输出目录&ndash;&gt;-->
<!--                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>-->
<!--                                </artifactItem>-->
<!--                                <artifactItem>-->
<!--                                    <groupId>com.midea</groupId>-->
<!--                                    <artifactId>cloud-biz-api-pj</artifactId>-->
<!--                                    <version>1.0-SNAPSHOT</version>-->
<!--                                    &lt;!&ndash; 设置为false，依赖解压到目录时不会进行覆盖，设置为true则会覆盖 &ndash;&gt;-->
<!--                                    <overWrite>false</overWrite>-->
<!--                                    &lt;!&ndash; 目标class文件输出目录&ndash;&gt;-->
<!--                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>-->
<!--                                </artifactItem>-->
<!--                                <artifactItem>-->
<!--                                    <groupId>com.midea</groupId>-->
<!--                                    <artifactId>cloud-biz-commons-pj</artifactId>-->
<!--                                    <version>1.0-SNAPSHOT</version>-->
<!--                                    &lt;!&ndash; 设置为false，依赖解压到目录时不会进行覆盖，设置为true则会覆盖 &ndash;&gt;-->
<!--                                    <overWrite>false</overWrite>-->
<!--                                    &lt;!&ndash; 目标class文件输出目录&ndash;&gt;-->
<!--                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>-->
<!--                                </artifactItem>-->
<!--                            </artifactItems>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
        </plugins>
    </build>
</project>