
ALTER TABLE `scc_sou_order_result`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称',
    ADD COLUMN `START_BPM_NOTICE_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '中标通知bpm发起人账号',
	ADD COLUMN `START_BPM_NOTICE_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT '中标通知bpm发起人名称';
