CREATE TABLE IF NOT EXISTS `scc_pj_sign_feign` (
    `SIGN_FEIGN_ID` bigint(20) NOT NULL COMMENT '主键ID',
    `FEIGN_URL_PATH` varchar(50) DEFAULT NULL COMMENT 'FEIGN的url前缀值',
    `FEIGN_CLASS_PATH` varchar(150) DEFAULT NULL COMMENT 'FEIGN的文件全路径值',
    `CREATED_ID` bigint(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY` varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE` datetime NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP` varchar(150) NOT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY` varchar(50) DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE` datetime DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP` varchar(150) DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID` varchar(30) DEFAULT NULL COMMENT '租户ID',
    `VERSION` bigint(20) DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`SIGN_FEIGN_ID`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='契约回调模块feign路径配置';