CREATE TABLE IF NOT EXISTS `scc_pj_sign_order` (
    `SIGN_ORDER_ID` bigint(20) NOT NULL COMMENT '主键ID',
    `ORDER_TYPE` varchar(50) DEFAULT NULL COMMENT '业务单据类型',
    `SIGN_FILE_ID` varchar(50) DEFAULT NULL COMMENT '合同文档ID',
    `SIGN_ID` bigint(20) DEFAULT NULL COMMENT '签署单ID',
    `SRM_ORDER_ID` bigint(20) DEFAULT NULL COMMENT 'SRM业务单据ID',
    `SIGN_STATUS` varchar(20) DEFAULT NULL COMMENT '盖章状态',
    `CREATED_ID` bigint(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY` varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE` datetime NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP` varchar(150) NOT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY` varchar(50) DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE` datetime DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP` varchar(150) DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID` varchar(30) DEFAULT NULL COMMENT '租户ID',
    `VERSION` bigint(20) DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`SIGN_ORDER_ID`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='签署业务单据关系表';


CREATE TABLE IF NOT EXISTS `scc_pj_sign_order_file` (
    `SIGN_ORDER_FILE_ID` bigint(20) NOT NULL COMMENT '主键ID',
    `SIGN_ORDER_ID` bigint(20) DEFAULT NULL COMMENT '签署业务单据关系表ID',
    `ORDER_FILE_ID` bigint(20) DEFAULT NULL COMMENT '业务单据附件ID',
    `SIGN_FILE_ID` varchar(50) DEFAULT NULL COMMENT '多文件合成合同文档ID',
    `File_Name` varchar(500) DEFAULT NULL COMMENT '文件名称',
    `FROM_TYPE` varchar(50) DEFAULT NULL COMMENT '来源类型：SRM、长城',
    `CREATED_ID` bigint(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY` varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE` datetime NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP` varchar(150) NOT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY` varchar(50) DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE` datetime DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP` varchar(150) DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID` varchar(30) DEFAULT NULL COMMENT '租户ID',
    `VERSION` bigint(20) DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`SIGN_ORDER_FILE_ID`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='签署业务附件关系表';



CREATE TABLE IF NOT EXISTS `scc_pj_sign_template` (
    `TEMPLATE_HEAD_ID` bigint(20) NOT NULL COMMENT '主键ID',
    `ORDER_TYPE` varchar(150) DEFAULT NULL COMMENT '业务类型编码',
    `ORDER_TYPE_NEME` varchar(150) DEFAULT NULL COMMENT '业务类型名称',
    `FEIGN_VALUE` varchar(50) DEFAULT NULL COMMENT 'FEIGN的value值',
    `BUSSINESS_CLASS` varchar(1000) DEFAULT NULL COMMENT '业务服务',
    `CREATED_ID` bigint(20) NOT NULL COMMENT '创建人ID',
    `CREATED_BY` varchar(50) NOT NULL COMMENT '创建人',
    `CREATION_DATE` datetime NOT NULL COMMENT '创建时间',
    `CREATED_BY_IP` varchar(150) NOT NULL COMMENT '创建人IP',
    `CREATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '最后更新人ID',
    `LAST_UPDATED_BY` varchar(50) DEFAULT NULL COMMENT '更新人',
    `LAST_UPDATE_DATE` datetime DEFAULT NULL COMMENT '最后更新时间',
    `LAST_UPDATED_BY_IP` varchar(150) DEFAULT NULL COMMENT '最后更新人IP',
    `LAST_UPDATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名',
    `TENANT_ID` varchar(30) DEFAULT NULL COMMENT '租户ID',
    `VERSION` bigint(20) DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`TEMPLATE_HEAD_ID`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='契约锁流程配置表';

