ALTER TABLE `scc_commit_task_param`
    CHANGE COLUMN `PARAM` `SUBMIT_PARAM` TEXT NULL DEFAULT NULL COMMENT '提交参数' COLLATE 'utf8mb4_unicode_ci' AFTER `BUSSINESS_TYPE`,
    ADD COLUMN `PREDICT_ACTIVITY_PARAM` TEXT NULL DEFAULT NULL COMMENT '预执行返回的审批节点数据' COLLATE 'utf8mb4_general_ci' AFTER `SUBMIT_PARAM`;
