CREATE TABLE IF NOT EXISTS `scc_pj_sap_company_intf`  (
  `SAP_COMPANY_INTF_ID` bigint(20) NOT NULL COMMENT '业务系统唯一ID',
  `ORG_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '供应商编码',
  `SUP_STATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '供供应商来源状态（ADD新增 UPDATE 修改）',
  `CREATION_DATE` datetime(0) NULL DEFAULT NULL COMMENT '创建时间 （格式：yyyy-MM-dd HH:mm:ss）',
  `CREATED_BY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建人',
  `PROCESS_STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '处理状态，PENDING：未处理，COMPLETED：处理完成，ERROR：处理错误',
  `PROCESS_MESSAGE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '处理信息',
  `PROCESS_DATE` datetime(6) NULL DEFAULT NULL COMMENT '处理时间',
  `APP_NUM` int(11) NULL DEFAULT 0 COMMENT '重试次数',
  `CREATED_ID` bigint(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `CREATED_BY_IP` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建人IP',
  `CREATED_FULL_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建人姓名',
  `LAST_UPDATED_ID` bigint(20) NULL DEFAULT NULL COMMENT '最后更新人ID',
  `LAST_UPDATED_BY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '更新人',
  `LAST_UPDATE_DATE` datetime(0) NULL DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATED_BY_IP` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '最后更新人IP',
  `LAST_UPDATED_FULL_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '最后更新人姓名',
  `TENANT_ID` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户ID',
  `VERSION` bigint(20) NULL DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`SAP_COMPANY_INTF_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic COMMENT='供应商同步SAP记录表';

