create table scc_npm_project_score_warning
(
    WARNING_ID                 bigint(20)           not null comment '主键ID'
        primary key,
    WARNING_CODE               varchar(50)          null comment '预警单据号',
    WARNING_NAME               varchar(250)         null comment '预警主题',
    PROJECT_SCORE_ITEMS_ID     bigint(20)           null comment '评分项目ID',
    PROJECT_NAME               varchar(250)         null comment '评分项目名称',
    OU_ORGANIZATION_ID         bigint(20)           null comment '公司id',
    OU_ORGANIZATION_CODE       varchar(100)         null comment '公司编码',
    OU_ORGANIZATION_NAME       varchar(150)         null comment '公司名称',
    PERF_MODEL_TYPE            varchar(50)          null comment '预警类型',
    WARNING_STATUS             varchar(50)          null comment '预警状态',
    READ_STATUS                varchar(10)          null comment '查看状态(Y/N)',
    BU_ORGANIZATION_ID         bigint(20)           null comment '板块id',
    BU_ORGANIZATION_CODE       varchar(100)         null comment '板块编码',
    BU_ORGANIZATION_NAME       varchar(150)         null comment '板块名称',
    COMPANY_ID                 bigint(20)           null comment '供应商ID',
    COMPANY_CODE               varchar(50)          null comment '供应商编码',
    COMPANY_NAME               varchar(500)         null comment '供应商名称',
    BID_MANAGER                varchar(50)          null comment '招标负责人',
    BID_MANAGER_FULL_PATH      varchar(500)         null comment '招标负责人部门全路径',
    CONTRACT_MANAGER           varchar(50)          null comment '合同经办人',
    CONTRACT_MANAGER_FULL_PATH varchar(500)         null comment '合同经办人部门全路径',
    WARNING_REMARK             mediumtext           null comment '预警详情',
    CREATED_ID                 bigint(20)           not null comment '创建人ID',
    CREATED_BY                 varchar(50)          not null comment '创建人',
    CREATION_DATE              datetime             not null comment '创建时间',
    CREATED_BY_IP              varchar(150)         not null comment '创建人IP',
    CREATED_FULL_NAME          varchar(100)         null comment '创建人姓名',
    LAST_UPDATED_ID            bigint(20)           null comment '最后更新人ID',
    LAST_UPDATED_BY            varchar(50)          null comment '更新人',
    LAST_UPDATE_DATE           datetime             null comment '最后更新时间',
    LAST_UPDATED_BY_IP         varchar(150)         null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME     varchar(100)         null comment '最后更新人姓名',
    TENANT_ID                  varchar(30)          null comment '租户ID',
    VERSION                    bigint(20) default 0 null comment '版本号'
)
    comment '供应商预警单';