ALTER TABLE `scc_pr_requirement_head`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_npm_pr_require_head`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';
ALTER TABLE `scc_npm_pr_require_cancel`
    ADD COLUMN `START_BPM_USERNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人账号',
	ADD COLUMN `START_BPM_NICKNAME` VARCHAR(50) NULL DEFAULT '' COMMENT 'bpm发起人名称';