CREATE TABLE `scc_npm_invoice_principal` (
     `PRINCIPAL_ID` bigint(20) NOT NULL COMMENT '主键,id',
     `ORG_ID` bigint(20) DEFAULT NULL COMMENT '业务实体id',
     `ORG_CODE` varchar(50) DEFAULT NULL COMMENT '业务实体编码',
     `ORG_NAME` varchar(100) DEFAULT NULL COMMENT '业务实体名称',
     `PRINCIPAL_CODE` varchar(50) DEFAULT NULL COMMENT '开票主体编码',
     `PRINCIPAL_NAME` varchar(100) DEFAULT NULL COMMENT '开票主体名称',
     `CREATED_ID` bigint(20) NOT NULL COMMENT '创建人ID',
     `CREATED_BY` varchar(50) NOT NULL COMMENT '创建人',
     `CREATION_DATE` datetime NOT NULL COMMENT '创建时间',
     `CREATED_BY_IP` varchar(150) NOT NULL COMMENT '创建人IP',
     `CREATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
     `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '最后更新人ID',
     `LAST_UPDATED_BY` varchar(50) DEFAULT NULL COMMENT '更新人',
     `LAST_UPDATE_DATE` datetime DEFAULT NULL COMMENT '最后更新时间',
     `LAST_UPDATED_BY_IP` varchar(150) DEFAULT NULL COMMENT '最后更新人IP',
     `LAST_UPDATED_FULL_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名',
     `TENANT_ID` varchar(30) DEFAULT NULL COMMENT '租户ID',
     `VERSION` bigint(20) DEFAULT 0 COMMENT '版本号',
     PRIMARY KEY (`PRINCIPAL_ID`),
     UNIQUE KEY `scc_npm_invoice_principal_ORG_ID_IDX` (`ORG_ID`) USING BTREE
) ENGINE=InnoDB COMMENT='开票主体';