ALTER TABLE `scc_sc_delivery_note_detail`
    CHANGE COLUMN `EXT_STORAGE_QTY` `EXT_STORAGE_QTY` DECIMAL(30,8) NULL DEFAULT 0 COMMENT '已入库数量',
    CHANGE COLUMN `EXT_CANCEL_QTY` `EXT_CANCEL_QTY` DECIMAL(30,8) NULL DEFAULT 0 COMMENT '已取消数量';
