create table scc_npm_pr_require_head (
    REQUIREMENT_HEAD_ID             bigint              not null comment 'ID' primary key,
    ORG_BU_ID                       bigint              null comment '所属板块ID',
    ORG_BU_CODE                     varchar(50)         null comment '所属板块编码',
    ORG_BU_NAME                     varchar(255)        null comment '所属板块名称',
    REQUIRE_FROM                    varchar(30)         null comment '需求来源',
    NO_REPORT_MONTH_PLAN_REASON     varchar(300)        null comment '未报月度计划原因',
    PROJECT_NAME                    varchar(80)         null comment '项目名称',
    PROJECT_MONTH                   int                 null comment '月份',
    INVEST_NO                       varchar(50)         null comment '投资编号',
    REQUIRE_QUANTITY                varchar(50)         null comment '数量/规模',
    TOTAL_AMOUNT_BY_TEN_KILO        decimal(24,8)       null comment '概算金额(万元)',
    NEED_PUBLIC                     char(1)             not null comment '是否公示',
    NO_PUBLIC_REASON                varchar(300)        null comment '不公示理由',
    PUBLIC_END_TIME                 date                null comment '公示截止时间',
    PROJECT_ADDRESS                 varchar(255)        null comment '项目所在地',
    PREFIX_TECH_DISCUSSION          char(1)             not null comment '前置技术交流意向',
    SEND_SOU_PROFILE_END_DATE       date                null comment '递交招标资料时间',
    PROJECT_PLAN_ID                 bigint              null comment '项目计划ID',
    PLAN_NO                         varchar(50)         null comment '项目计划编号',
    SPECIAL_SOU_TYPE                varchar(30)         null comment '特殊招标类型',
    SPECIAL_REASON                  varchar(300)        null comment '特殊原因',
    REQUIRE_PRODUCT_DATE            date                null comment '需求产生时间',
    REQUIRE_PRODUCT_FILE_ID         bigint              null comment '需求产生时间附件ID',
    REQUIRE_PRODUCT_FILE_NAME       varchar(150)        null comment '需求产生时间附件名称',
    REMAINING_DAY                   decimal(12,4)       null comment '剩余时间',
    DELIVERY_DAY                    decimal(12,4)       null comment '工期交货期',
    DELIVERY_DAY_FILE_ID            bigint              null comment '工期交货期附件ID',
    DELIVERY_DAY_FILE_NAME          varchar(150)        null comment '工期交货期附件名称',
    SIGN_CONTRACT_DAY               decimal(12,4)       null comment '签合同用时',
    PUT_INTO_USE_DATE               decimal(12,4)       null comment '投入使用时间',
    PUT_INTO_USE_DATE_FILE_ID       bigint              null comment '投入使用时间附件ID',
    PUT_INTO_USE_DATE_FILE_NAME     varchar(150)        null comment '投入使用时间附件名称',
    OTHER_SPECIAL_REASON            varchar(300)        null comment '其他特殊原因补充',
    REMAINING_DAY                   decimal(24,8)       null comment '剩余时间',
    PROJECT_OVERVIEW                text                null comment '项目概况及范围',
    TECH_REQUIRE                    text                null comment '技术要求',
    PERFORMANCE_REQUIRE             text                null comment '业绩要求',
    VENDOR_QUALIFICATION_REQUIRE    text                null comment '供应商资质要求',
    HAS_ASSIGNED                    char(1) default 'N' not null comment '是否已分配(招标+供应商负责人)',
    HAS_SEND_SOU_PROFILE            char(1) default 'N' not null comment '是否已递交招标资料',
    HAS_CREATE_SOU                  char(1) default 'N' not null comment '是否已创建寻源',
    HAS_CREATE_SOU_REQ              char(1) default 'N' not null comment '是否已创建寻源需求',
    HAS_CREATE_VENDOR_RECOMMEND     char(1) default 'N' not null comment '是否已创建供应商推荐',
    HAS_SUBMIT                      char(1) default 'N' not null comment '是否已提交',
    EARNEST_MONEY                   decimal(24,8)       null comment '意向金金额(万元)',
    APPROVAL_PASS_TIME              datetime            null comment '需求审批通过时间',
    SOU_REQ_STATUS                  varchar(30)         null comment '需求状态',
    SEND_SOU_PROFILE_STATUS         varchar(30)         null comment '招标资料状态',
    AFTER_TOTAL_AMOUNT_BY_TEN_KILO  decimal(24,8)       null comment '变更后概算金额(万元)',
    CHANGE_REASON                   text                null comment '变更原因',
    CHANGE_REQUIREMENT_HEAD_ID      bigint              null comment '变更来源计划ID',
    CHANGE_REQUIREMENT_HEAD_NUM     varchar(50)         null comment '变更来源计划单号',
    REQ_CANCEL_REASON               text                null comment '需求取消原因',
    SOU_TYPE                        varchar(10)         null comment '关联寻源单类型',
    SOU_PROJECT_ID                  bigint              null comment '关联寻源单ID',
    SOU_NO                          varchar(50)         null comment '关联寻源单号',
    SOU_NAME                        varchar(255)        null comment '关联寻源单名称',
    SOU_REQ_ID                      bigint              null comment '关联寻源需求ID',
    SOU_REQ_NO                      varchar(50)         null comment '关联寻源需求编号',
    RECOMMEND_VENDOR_BILL_ID        bigint              null comment '关联推荐供应商单据ID',
    RECOMMEND_VENDOR_BILL_NO        varchar(50)         null comment '关联推荐供应商单据编码',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划拓展表';


create table scc_npm_pr_require_group (
    REQUIREMENT_GROUP_ID            bigint              not null comment 'ID' primary key,
    REQUIREMENT_HEAD_ID             bigint              not null comment '招标计划ID',
    USER_ID                         bigint              null comment '用户ID',
    USERNAME                        varchar(50)         null comment '用户账号',
    FULL_NAME                       varchar(255)        null comment '用户昵称',
    GROUP_TYPE                      varchar(80)         null comment '职责类型',
    PHONE                           varchar(50)         null comment '联系方式',
    EMAIL                           varchar(200)        null comment '邮箱',
    DEPARTMENT_ID                   varchar(100)        null comment '所属部门ID',
    DEPARTMENT_NAME                 varchar(100)        null comment '所属部门名称',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划工作成员表';


create table scc_npm_pr_require_vendor (
    REQUIREMENT_VENDOR_ID           bigint              not null comment 'ID' primary key,
    REQUIREMENT_HEAD_ID             bigint              not null comment '招标计划ID',
    VENDOR_ID                       bigint              null comment '供应商ID',
    VENDOR_CODE                     varchar(50)         null comment '供应商账号',
    VENDOR_NAME                     varchar(255)        null comment '供应商昵称',
    CONTACT_NAME                    varchar(50)         null comment '联系人名称',
    PHONE                           varchar(50)         null comment '联系方式',
    EMAIL                           varchar(200)        null comment '邮箱',
    RECOMMEND_FROM                  varchar(30)         null comment '推荐来源',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划推荐供应商表';


create table scc_npm_pr_require_attach (
    REQUIREMENT_ATTACH_ID           bigint              not null comment 'ID' primary key,
    REQUIREMENT_HEAD_ID             bigint              not null comment '招标计划ID',
    FILE_TYPE                       varchar(30)         null comment '文件类型',
    FILE_ID                         bigint              null comment '文件ID',
    FILE_NAME                       varchar(255)        null comment '文件名称',
    UPDATE_DATE                     date                null comment '上传时间',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划附件表';

create table scc_npm_pr_project_plan (
    PROJECT_PLAN_ID                 bigint              not null comment 'ID' primary key,
    PROJECT_NAME                    varchar(80)         not null comment '项目名称',
    SCENE_TYPE                      varchar(30)         not null comment '应用场景',
    INIT_DATE                       date                null comment '立项时间',
    DEPARTMENT_ID                   varchar(30)         null comment '投资部门ID',
    DEPARTMENT_NAME                 varchar(255)        null comment '投资部门名称',
    INIT_AMOUNT                     decimal(24,8)       null comment '立项金额',
    PLAN_NO                         varchar(80)         null comment '计划编号',
    PLAN_ADDRESS                    varchar(255)        null comment '投资地点',
    PLAN_LEVEL                      varchar(30)         null comment '项目级别',
    PLAN_STATUS                     varchar(30)         null comment '项目状态',
    REQUIREMENT_HEAD_ID             bigint(20)          null comment '被引用的招标计划ID',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划项目计划表';


create table scc_npm_pr_require_cancel (
    REQUIREMENT_CANCEL_ID           bigint              not null comment 'ID' primary key,
    REQUIREMENT_CANCEL_NO           varchar(50)         not null comment '计划取消编号',
    CANCEL_STATUS                   varchar(30)         not null comment '计划取消状态',
    DEPARTMENT_ID                   varchar(50)         null comment '申请部门ID',
    DEPARTMENT_NAME                 varchar(150)        null comment '申请部门名称',
    APPLY_DATE                      date                null comment '申请日期',
    APPLY_BY_ID                     bigint              null comment '申请人ID',
    APPLY_BY                        varchar(50)         null comment '申请人账号',
    APPLY_BY_NICKNAME               varchar(150)        null comment '申请人昵称',
    CANCEL_REASON                   text                null comment '取消原因',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划 - 计划取消';

create table scc_npm_pr_require_cancel_file (
    REQUIREMENT_CANCEL_ATTACH_ID    bigint              not null comment 'ID' primary key,
    REQUIREMENT_CANCEL_ID           bigint              not null comment '计划取消ID',
    FILE_ID                         bigint              null comment '文件ID',
    FILE_NAME                       varchar(150)        null comment '文件名称',
    UPLOAD_TIME                     datetime            null comment '上传时间',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划 - 计划取消附件';

create table scc_npm_pr_require_cancel_line (
    REQUIREMENT_CANCEL_LINE_ID      bigint              not null comment 'ID' primary key,
    REQUIREMENT_CANCEL_ID           bigint              not null comment '计划取消ID',
    REQUIREMENT_HEAD_ID             bigint              null comment '招标计划ID',
    SORT_INDEX                      int                 not null comment '排序',

    CREATED_ID                      bigint              not null comment '创建人ID',
    CREATED_BY                      varchar(50)         not null comment '创建人',
    CREATION_DATE                   datetime            not null comment '创建时间',
    CREATED_BY_IP                   varchar(150)        not null comment '创建人IP',
    CREATED_FULL_NAME               varchar(100)        null comment '创建人姓名',
    LAST_UPDATED_ID                 bigint              null comment '最后更新人ID',
    LAST_UPDATED_BY                 varchar(50)         null comment '更新人',
    LAST_UPDATE_DATE                datetime            null comment '最后更新时间',
    LAST_UPDATED_BY_IP              varchar(150)        null comment '最后更新人IP',
    LAST_UPDATED_FULL_NAME          varchar(100)        null comment '最后更新人姓名',
    TENANT_ID                       varchar(30)         null comment '租户ID',
    VERSION                         bigint default 0    null comment '版本号'
) comment '招标计划 - 计划取消明细';